### ISSUE TITLE
Missing @ngx-progressbar/core/core.ngfactory file in angular 5 app

### ISSUE THREAD

**Issue by davidkudera** [MurhafSousli/ngx-progressbar#100]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
- [ ] question
```

### OS and Version?

Ubuntu 17.04 LTS

### Versions

* node: v8.9.1
* yarn: 1.3.2
* ngx-progressbar/core: 3.0.1
* angular: 5.0.5
* angular/cli: 1.5.5
* ngtools/webpack: 1.8.5

### Repro steps

```bash
$ yarn add @ngx-progressbar/core
```

Register module to root `AppModule`:

```typescript
import {NgModule} from '@angular/core';
import {BrowserModule} from '@angular/platform-browser';
import {NgProgressModule} from '@ngx-progressbar/core';

import {AppRoutingModule} from './app-routing.module';
import {AppComponent} from './app.component';


@NgModule({
	imports: [
		BrowserModule,
		AppRoutingModule,
		NgProgressModule.forRoot(),
	],
	declarations: [
		AppComponent,
	],
	bootstrap: [AppComponent],
})
export class AppModule {}
```

### The log given by the failure

```
ERROR in ./app/app.component.ngfactory.js
Module not found: Error: Can't resolve '../node_modules/@ngx-progressbar/core/core.ngfactory' in '/path/to/app'
```

### Desired functionality

Being able to compile the project with ngx-progressbar.

### Mention any other details that might be useful

I'm using @ngtools/webpack with webpack.

**Comment by MurhafSousli** [comment]
Hi @davidkudera, can you reproduce the issue in a [stackblitz](https://stackblitz.com/edit/ngx-progressbar)?

**Comment by davidkudera** [comment]
Hello, I created test repository with minimum config from our app here: https://github.com/davidkudera/ngx-progressbar-core-issue-100

The problem is that we have multiple apps in one project with shared `node_modules` directory. And since all modules have their own `rootDir` specified in their `tsconfig.json` file, the shared `node_modules` is out of their context. Because of this angular don't try to process these files and your package.

I'm not sure if there is something you can do in this package, or it needs to be done in `angular-cli`, or if I need to change our config somehow.

**Comment by MurhafSousli** [comment]
@davidkudera I am not sure, I am not an expert in building env, but I compile the package with [ng-packagr](http://spektrakel.de/ng-packagr/) In the worst case scenario, you can include the source files

**Comment by davidkudera** [comment]
I think we can close this issue for now.

I'll create a new issue in angular-cli repository and temporarily add second `package.json` and `node_modules` into our "inner" module. I'll let you know if I'll have any news on this.

Thanks for your help and package 😉

**Comment by MurhafSousli** [comment]
welcome
