### ISSUE TITLE
Metadata version mismatch

### ISSUE THREAD

**Issue by mac10046** [MurhafSousli/ngx-progressbar#102]
Hi, I am getting this error on ng serve:

ERROR in Metadata version mismatch for module D:/***/node_modules/@ngx-progressbar/core/core.d.ts, found version 4, expected 3, resolving symbol AppModule in D:/***/src/app/app.module.ts, resolving symbol AppModule in D:/***/src/app/app.module.ts, resolving symbol AppModule in D:/***/src/app/app.module.ts

My Specification are : 
node -v = v8.9.2
Global angular-cli : 1.6.0
Project angular-cli : 1.0.3
angular/core: ^4.1.2

**Comment by MurhafSousli** [comment]
Hi @mac10046 For Angular 4, use the old package `npm i ngx-progressbar` [documentation is here](https://github.com/MurhafSousli/ngx-progressbar/wiki)
