### ISSUE TITLE
Feature request: Configurable overlay with progress bar

### ISSUE THREAD

**Issue by lazyspark** [MurhafSousli/ngx-progressbar#103]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x] feature request
- [ ] question
```

### OS and Version?
Windows 7

### Repro steps
Configure the application to use ngx-progressbar-core. 
The loader and spinner shows up
The page does not have an overlay

### The log given by the failure
Feature request

### Desired functionality
A configurable overlay on the whole page. Not allowing any action until the request is complete

**Comment by MurhafSousli** [comment]
Hi @lazyspark This can be easily done using `started/ended` events.
I think it would be more convenient to let the user design his own custom overlay.

If you have a generic overlay design that you think would useful to be added out of the box, create one with this [stackbilitz](https://stackblitz.com/edit/ngx-progressbar)

**Comment by junaidkiyani** [comment]
HI @MurhafSousli  can you give me us a code snippet

**Comment by patsub** [comment]
Hi @MurhafSousli 
I am trying to achieve the same overlay page as explained here, but still i am getting the default view. Not same as here -> "[](https://stackblitz.com/edit/ngx-progressbar-vubvhp)"
app.module.ts
```
import { HttpClientModule, HTTP_INTERCEPTORS } from '@angular/common/http';
import { NgProgressModule, NgProgressInterceptor } from 'ngx-progressbar';

imports: [    
    HttpClientModule,
    NgProgressModule,
  ],
 providers: [
{ provide: HTTP_INTERCEPTORS, useClass: NgProgressInterceptor, multi: true }
  ],
  bootstrap: [AppComponent],
})
```
app.component.html
```
 <ng-progress #progressBar>
      </ng-progress>
    
      <div class="block-screen" *ngIf="progressBar.isStarted"><b>Please wait...</b></div>
    </div>
```
app.component,css
```
.block-screen {
    position: fixed;
    left: 0;
    right: 0;
    top: 0;
    bottom: 0;
    background: rgba(0,0,0, 0.6);
    display: flex;
    justify-content: center;
    align-items: center;
    color: white;
  }
```
Nothing on app.component.ts.
