### ISSUE TITLE
Question: is there a way to change color?

### ISSUE THREAD

**Issue by yanivamrami** [MurhafSousli/ngx-progressbar#104]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [X] question
```

### OS and Version?
Windows 10

### Versions
Node: v9.2.0
Npm: 5.5.1
Angular: 5.0.3

### Repro steps
Not Relevant

### The log given by the failure
Not Relevant

### Desired functionality
Ability to change progress bar color

### Mention any other details that might be useful
Not Relevant

**Comment by fchiumeo** [comment]
[readme](https://github.com/MurhafSousli/ngx-progressbar#ngprogress-component)

> [color]: any color format #1eb77f, brown, rgb(30, 183, 127).
>Set the progressbar color, default: #29d

**Comment by yanivamrami** [comment]
Thanks! I missed that in the readme...
