### ISSUE TITLE
Automagic loading bar with Firebase

### ISSUE THREAD

**Issue by mithleshjs** [MurhafSousli/ngx-progressbar#106]
I use AngularFire2 library to connect with Firebase. I want to show progress bar whenever my app fetches data from Firebase. But this library is not intercepting any HTTP request that is made to the Firebase.

**Comment by MurhafSousli** [comment]
@mithleshjs Currently there is no automatic mode for Firebase

**Comment by mithleshjs** [comment]
@MurhafSousli Would Firebase be supported in some future release?

**Comment by MurhafSousli** [comment]
@mithleshjs sorry I haven't noticed your comment.
Yea, it is possible. meanwhile, PRs are welcome

**Comment by MurhafSousli** [comment]
It turns out that interceptors are not a good fit for a real-time data store like Firebase.
