### ISSUE TITLE
Unable to apply some CSS properties to the ng-progress and bar-shadow divs

### ISSUE THREAD

**Issue by pdotmad** [MurhafSousli/ngx-progressbar#109]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
- [ ] question
```

### OS and Version?
Windows 10

### Versions
node v6.11.3
npm 3.10.10

*From the package.json file in my ionic project:*
@angular/* : 4.4.3
"angularfire2": "^5.0.0-rc.3"

### Repro steps
I used the `<ng-progress>` tag in the `<ion-content>` tag in the `myPage.html` file:
```
...
<ion-content>
  <ion-card>
     <ng-progress></ng-progress>
...
  </ion-card>
</ion-content>
```
I'm unable to apply the `position:relative` property of the `.ng-progress` class and the `display:none` property of the `.bar-shadow` class in the `myPage.scss` file. There might be some more CSS properties that don't get applied to these and other classes. However, I must note here that I was able to use the `margin-top:100px` property on these classes.

This issue did not appear when I removed ngx-progressbar and installed the deprecated ng2-progressbar, but then I ran into the ObjectUnsubscribedError issue for the deprecated ng2-progressbar.

### The log given by the failure
NA.

### Desired functionality
NA.

**Comment by MurhafSousli** [comment]
@pdotmad ng2-progressbar is deperecated
Before I can answer I need to know:
The version of `ngx-progressbar` are you using.
The code that did not work for you.

Generally, you should use `!important` when you override progress bar styles

**Comment by pdotmad** [comment]
Thanks for the prompt response. It was naive of me to not think of adding `!important` in my CSS. It's working perfectly now. Sorry to bother you with  that silly query.
