### ISSUE TITLE
Automagic loading bar keeps loading forever in angular 5 

### ISSUE THREAD

**Issue by RbkGh** [MurhafSousli/ngx-progressbar#110]
Once library is setup in angular 5.0.0 and the tag is placed in the AppComponent html ,any first http request initiates the slim loading bar successfully but the loading bar never stops loading even when there are no more http requests.

**Comment by MurhafSousli** [comment]
Hi @RbkGh which Http are you using, please reproduce the issue with a stackblitz
 - [http client stackblitz](https://stackblitz.com/edit/ngx-progressbar-httpclient)
 - [http stackblitz](https://stackblitz.com/edit/ngx-progressbar-http)

**Comment by RbkGh** [comment]
@MurhafSousli,i just removed the custom http interceptor i had in my 'providers' in app.module.ts and it is working,seems there is a conflict with custom http interceptors.

i made a stackblitz here https://stackblitz.com/edit/ngx-progressbar-httpclient-burh5q which works with a custom http interceptor anyway.

**Comment by MurhafSousli** [comment]
I guess that fixes the problem
