### ISSUE TITLE
Module not found: Error: Can't resolve 'rxjs/operators'

### ISSUE THREAD

**Issue by ziaulain** [MurhafSousli/ngx-progressbar#112]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
- [] question
```

### OS and Version?
Mac os: High sierra
10.13.2
### Versions

angular/cdk: 2.0.0-beta.12
angular/cli: 1.5.0
angular/language-service: 4.4.3
angular/material: 2.0.0-beta.12
angular-devkit/build-optimizer: 0.0.33
angular-devkit/core: 0.0.20
angular-devkit/schematics: 0.0.36
ngtools/json-schema: 1.1.0
ngtools/webpack: 1.8.0
schematics/angular: 0.1.5
typescript: 2.3.4
webpack: 3.8.1

### Repro steps

Install NgProgressRouterModule

If you need the progress bar to start for navigating between your app routes, add this module

import { HttpModule } from '@angular/http';
import { NgProgressModule } from '@ngx-progressbar/core';
import { NgProgressHttpModule } from '@ngx-progressbar/http';

@NgModule({
  imports: [
    ....
    NgProgressModule.forRoot(),
    NgProgressHttpModule,
    ...
  ],
})
Component in AppComponent template
<ng-progress></ng-progress>

### The log given by the failure
ERROR in ./node_modules/@ngx-progressbar/core/esm5/ngx-progressbar-core.js
Module not found: Error: Can't resolve 'rxjs/operators'

**Comment by MurhafSousli** [comment]
@ziaulain when does the error occur? with `NgProgressModule` or `NgProgressRouterModule`
Here is a working plunkr https://stackblitz.com/edit/ngx-progressbar-router

**Comment by ziaulain** [comment]
The problem seems to be is with the version. I was using some other plugin and was having the same issue. After downgrading the version of the plugin it started working.

**Comment by lovesinghchahal** [comment]
npm install rxjs@6 rxjs-compat@6 --save

**Comment by tonywr71** [comment]
If it is a compatibility issue, can someone please explain the correct way to handle the operators? map, catch, etc
