### ISSUE TITLE
Update npm package

### ISSUE THREAD

**Issue by ArtworkAD** [MurhafSousli/ngx-progressbar#117]
https://www.npmjs.com/package/ngx-progressbar is still showing 2.1.1. Please update to latest version

**Comment by MurhafSousli** [comment]
@ArtworkAD for latest version use `@ngx-progressbar/core`

**Comment by fchiumeo** [comment]
[maybe deprecated the package](https://docs.npmjs.com/cli/deprecate)

**Comment by MurhafSousli** [comment]
@fchiumeo it is not deprecated some people might want to use that version
