### ISSUE TITLE
NgProgressHttpModule has to be imported in each submodule that has http calls

### ISSUE THREAD

**Issue by ArtworkAD** [MurhafSousli/ngx-progressbar#120]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x] feature request
- [ ] question
```

### OS and Version?

OSX Yosemite

### Versions

angular/cli: 1.6.3
Angular v5.0

### Repro steps

```
ng new my-app
cd my-app
npm install --save @ngx-progressbar/core @ngx-progressbar/http
```

in `app.module` import

    NgProgressModule.forRoot(),
    NgProgressHttpModule

Create another submodule

    ng generate module test

in `test.component` I make a simple request like

    this.http.get(...).subscribe()

Loading bar won't display.

Import `NgProgressHttpModule` in `test.module`, and the loading bar will be displayed correctly.

### Desired functionality

Import of `NgProgressHttpModule` should only be required in `app.module`. If it is a requirement to import it in any module that has http calls, then please add this information to the docs.

**Comment by MurhafSousli** [comment]
@ArtworkAD [HttpModule](https://angular.io/api/http/HttpModule) is deprecated therefore **NgProgressHttpModule** is now works for HttpClient
If you are not planning to use HttpClient, you can use the previous version `@ngx-progressbar/http@3.0.2`
[Documentation for v3.x](https://github.com/MurhafSousli/ngx-progressbar/blob/master/README_V3.md)

**Comment by ArtworkAD** [comment]
@MurhafSousli  I am using `HttpClientModule`

**Comment by MurhafSousli** [comment]
@ArtworkAD Can you reproduce it in [stackblitz](https://stackblitz.com/edit/ngx-progressbar-http)

**Comment by ArtworkAD** [comment]
@MurhafSousli https://stackblitz.com/edit/ngx-progressbar-http-vkkaqg 

I forked your stackblitz and added another module. This module currently imports `NgProgressHttpModule` and the loading bar is showing up. However when you remove the import, the loading bar disappears.

So my conclusion is: NgProgressHttpModule has to be imported in every module in order for the loading bar to show up in that module.

**Comment by MurhafSousli** [comment]
@ArtworkAD You should not import `HttpClientModule` in child module.
[fixed stackblitz](https://stackblitz.com/edit/ngx-progressbar-http-ju192g?file=app/country/country.module.ts)

**Comment by ArtworkAD** [comment]
@MurhafSousli what did you change to make it work?

**Comment by MurhafSousli** [comment]
Just removed `HttpClientModule` and `NgProgressHttpModule` that you had in the child module
