### ISSUE TITLE
Non encapsulated styles affecting our own styles

### ISSUE THREAD

**Issue by davidkudera** [MurhafSousli/ngx-progressbar#125]
Hello, right now the progress bar uses `ViewEncapsulation.None` which is affecting our own styles. This is quite problematic since it also uses such a common class names like `.bar` or `.spinner`. 

From what I was able to find, the prefered way for external libraries should be isolation of css throught encapsulation. Is there any plan to change the current behavior?

### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x] feature request
- [ ] question
```

### OS and Version?
Ubuntu

### Versions
`@ngx-progressbar/core`: 4.0.1

### Repro steps
Install and enable ngx-progressbar and write custom styles with eg. `.spinner` class.

### Desired functionality
Don't affect the website's CSS.

**Comment by MurhafSousli** [comment]
@davidkudera I kept on the `ViewEncapsulation.None` to ease overriding styles, but all the classes are now prefixed with `ng-`

**Comment by davidkudera** [comment]
That works good enough for us. Thank you so much :beers:

**Comment by MurhafSousli** [comment]
@davidkudera welcome
