### ISSUE TITLE
npm install --save @ngx-progressbar/core doesnt work

### ISSUE THREAD

**Issue by SaliZumberi** [MurhafSousli/ngx-progressbar#135]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
- [ ] question
```

### Versions

Angular CLI: 1.7.0 (e)
Node: 8.9.4
OS: win32 x64
Angular: 5.2.5
... common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

@angular/cli: 1.7.0
@angular-devkit/build-optimizer: 0.3.1
@angular-devkit/core: 0.3.1
@angular-devkit/schematics: 0.3.1
@ngtools/json-schema: 1.2.0
@ngtools/webpack: 1.10.0
@schematics/angular: 0.3.1
@schematics/package-update: 0.3.1
typescript: 2.4.2
webpack-concat-plugin: 1.4.0
webpack-dev-server: 2.7.1
webpack: 3.8.1

### Repro steps

npm install --save @ngx-progressbar/core

### The log given by the failure

λ npm install --save ngx-progressbar/core
npm ERR! Error while executing:
npm ERR! C:\Program Files\Git\cmd\git.EXE ls-remote -h -t ssh://git@github.com/ngx-progressbar/core.git
npm ERR!
npm ERR! Host key verification failed.
npm ERR! fatal: Could not read from remote repository.
npm ERR!
npm ERR! Please make sure you have the correct access rights
npm ERR! and the repository exists.
npm ERR!
npm ERR! exited with error code: 128

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\szu\AppData\Roaming\npm-cache\_logs\2018-02-21T10_24_08_940Z-debug.log

### Mention any other details that might be useful

Angualr 5 project

**Comment by MurhafSousli** [comment]
You forgot the **@** it is `npm install --save @ngx-progressbar/core`
