### ISSUE TITLE
No provider for NgProgress

### ISSUE THREAD

**Issue by jesusvalenzuelar** [MurhafSousli/ngx-progressbar#136]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report
- [ ] feature request
- [ ] question
```

### OS and Version?

> Windows 10 Pro (x64)

### Versions
Angular CLI: 1.6.6
Node: 8.9.1

### Repro steps
* `npm install --save @ngx-progressbar/core @ngx-progressbar/http-client`
* Add the required modules to AppModule:
```
import { HttpClientModule } from '@angular/common/http';
import { NgProgressModule } from '@ngx-progressbar/core';
import { NgProgressHttpClientModule } from '@ngx-progressbar/http-client';

@NgModule({
  imports: [
    HttpClientModule,
    NgProgressModule.forRoot(),
    NgProgressHttpClientModule
  ]
})
```

* In app.component.ts I added the tag:

```
@Component({
  selector: '#main-body-app',
  template: '**<ng-progress #progressBar></ng-progress>**<router-outlet></router-outlet>'
})
export class AppComponent implements OnInit {
}
```

### The log given by the failure
`ERROR Error: StaticInjectorError(AppModule)[InjectionToken HTTP_INTERCEPTORS -> NgProgress]: 
  StaticInjectorError(Platform: core)[InjectionToken HTTP_INTERCEPTORS -> NgProgress]: 
    NullInjectorError: No provider for NgProgress!
    at _NullInjector.get (core.js:994)
    at resolveToken (core.js:1292)
    at tryResolveToken (core.js:1234)
    at StaticInjector.get (core.js:1102)
    at resolveToken (core.js:1292)
    at tryResolveToken (core.js:1234)
    at StaticInjector.get (core.js:1102)
    at resolveNgModuleDep (core.js:10847)
    at _callFactory (core.js:10911)
    at _createProviderInstance$1 (core.js:10861)`

### Desired functionality
I have a routing module with sub-module lazy loading, I'd like to include the imports within routing module to allow sub modules use loading bar component.

### Mention any other details that might be useful
I already have sub-modules that I want to include the loading bar but it isn't working when compiling with **ng serve** command.

**Comment by jesusvalenzuelar** [comment]
I just found the solution for this issue, 
* Remove ngx-progressbar/http-client
> `npm uninstall @ngx-progressbar/http-client`
* Install ngx-progressbar/http
> `npm install --save @ngx-progressbar/http`
* Change all references of NgProgressHttpClientModule by NgProgressHttpModule even if you are using HttpClientModule.

Th solution was found in the issue #122

**Comment by jayzyaj** [comment]
I had the same issue but with Ionic 3. I did the same but it still shows the error. Any thoughts?

**Comment by briancaldass** [comment]
> Thanks @jesusvalenzuelar . It works!!!

it not working for me, help :(
