### ISSUE TITLE
InjectionToken HTTP_INTERCEPTORS -> NgProgress

### ISSUE THREAD

**Issue by jorgelub12** [MurhafSousli/ngx-progressbar#137]
### Bug Report or Feature Request (mark with an `x`)
```
- [X] bug report -> please search issues before submitting
- [ ] feature request
- [ ] question
```

### OS and Version?
> Windows 10

### Versions
```
Angular CLI: 1.7.0
Node: 8.9.1
OS: win32 x64
Angular: 5.2.5
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

@angular/cli: 1.7.0
@angular/http: 5.2.5
@angular/language-service: 5.0.4
@angular-devkit/build-optimizer: 0.3.1
@angular-devkit/core: 0.3.1
@angular-devkit/schematics: 0.3.1
@ngtools/json-schema: 1.2.0
@ngtools/webpack: 1.10.0
@schematics/angular: 0.3.1
@schematics/package-update: 0.3.1
typescript: 2.7.2
webpack: 3.11.0
```

### Repro steps
> Upading the packages.json to 5.2.5

### The log given by the failure
```
Error: StaticInjectorError(AppModule)[InjectionToken HTTP_INTERCEPTORS -> NgProgress]: 
StaticInjectorError(Platform: core)[InjectionToken HTTP_INTERCEPTORS -> NgProgress]: 
NullInjectorError: No provider for NgProgress!
```

### Mention any other details that might be useful
app.module:
```
imports: [
        BrowserModule,
        RouterModule,
        FormsModule,
        BsDropdownModule.forRoot(),
        NgProgressModule.forRoot(),
        NgProgressHttpClientModule
    ],
```

**Comment by MurhafSousli** [comment]
Which version of the plugin are you using?

**Comment by Bodeclas** [comment]
@jorgelub12 
I just found the solution for this issue,
Remove ngx-progressbar/http-client

`npm uninstall @ngx-progressbar/http-client`

Install ngx-progressbar/http

`npm install --save @ngx-progressbar/http`

Change all references of NgProgressHttpClientModule by NgProgressHttpModule even if you are using HttpClientModule.

- `@ngx-progressbar/http-client` package is deprecated, use `@ngx-progressbar/http` instead.

https://github.com/MurhafSousli/ngx-progressbar/blob/master/CHANGELOG.md

**Comment by briancaldass** [comment]
> NgProgressHttpModule

Its not working , help
