### ISSUE TITLE
Add a guide of upgrading from version 3 to 4

### ISSUE THREAD

**Issue by PoiScript** [MurhafSousli/ngx-progressbar#138]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x] feature request
- [ ] question
```

Since v4, we use `NgProgressHttpModule` which is imported form `@ngx-prgoressbar/http` to intercept HttpClient requests, instead of `NgProgressHttpClientModule` form `@ngx-progressbar/http-client`. This is quite a big breaking change, but it's not mentioned in the `README.md`.

**Comment by fchiumeo** [comment]
see [changelog](https://github.com/MurhafSousli/ngx-progressbar/blob/master/CHANGELOG.md#400l)

**Comment by MurhafSousli** [comment]
Breaking changes are mentioned in the [changelog](https://github.com/MurhafSousli/ngx-progressbar/blob/master/CHANGELOG.md#400)
