### ISSUE TITLE
'completed' event stream is not working but 'started' event is working

### ISSUE THREAD

**Issue by jayadrathamondal** [MurhafSousli/ngx-progressbar#139]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
- [ ] question
```

### OS and Version?

Ubuntu 16.04

### Versions

ng version:  1.7.2
node version: 8.9.4
npm version: 5.7.1

### Repro steps

Add `<ng-progress [thick]="true" [ease]="'easeInSine'" (started)="onLoaderStarted()" (completed)="onLoaderCompleted()"></ng-progress>` in any component html.
Both the functions are in same component, the functions does only a log.
onLoaderStarted function is getting called, but onLoaderCompleted is not getting called.
I'm using the automagic setup of ngx-progressbar

### The log given by the failure

No error

### Desired functionality

onLoaderStarted & onLoaderCompleted both should be called properly.

**Comment by MurhafSousli** [comment]
@jayadrathamondal the output is `(complete)` in the component.
but if you use `NgProgress` service then `complete()` is the function and `completed` is the event

**Comment by MurhafSousli** [comment]
@jayadrathamondal can you reproduce it, here is [automagic stackblitz](https://stackblitz.com/edit/ngx-progressbar-http?file=app%2Fapp.component.ts)

**Comment by jayadrathamondal** [comment]
I'm trying to reproduce it. Adding a automagic ngx progressbar has nothing but only the setup. And I'm not able to find any difference between your setup & mine. But in my setup 'completed' event is not getting triggered. I'm checking if any other module or library effecting anything.

**Comment by MurhafSousli** [comment]
@jayadrathamondal Did you give the progress bar an id?

**Comment by jayadrathamondal** [comment]
@MurhafSousli no I didnt. The loader is not working when I'm giving the ng-progress an id.
