### ISSUE TITLE
Update to support rxjs 6.0

### ISSUE THREAD

**Issue by mhosman** [MurhafSousli/ngx-progressbar#143]
This is a forced requirement in new Angular >= 6.0 rc0

**Comment by mhosman** [comment]
This enhacement would be great. Thank you!!!

**Comment by mmukarram** [comment]
Take a look at pull request #155 to upgrade the package to support Angular v6.0

**Comment by ggjersund** [comment]
Just wondering, is this why I get

`./node_modules/@ngx-progressbar/core/esm5/ngx-progressbar-core.js Module not found: Error: Can't resolve 'rxjs/BehaviorSubject' in '/Users/<username>/Development/work/work-frontend/node_modules/@ngx-progressbar/core/esm5'`

**Comment by iamimbohacker** [comment]
guys. when you will release an angular 6 supporn. my app is on fire without your progress bar)

**Comment by MurhafSousli** [comment]
A `5.0.0-rc.1` version is released, you might get an error when building using AOT, but this is a bug in Angular 6.0.0 and the error will be gone when they fix https://github.com/angular/angular/issues/23609

**Comment by MurhafSousli** [comment]
Will keep this open to avoid new duplicated issues

**Comment by krreet** [comment]
npm install ngx-progressbar@4.3.0 --save
npm ERR! code ETARGET
npm ERR! notarget No matching version found for ngx-progressbar@4.3.0
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

**Comment by miteshngandhi** [comment]
Hi,

Similar issue observed for version - 5.0.1
verbose stack ngx-progressbar: No matching version found for ngx-progressbar@^5.0.1

Replacing to below in package.json worked!
OLD:
"ngx-progressbar": "^5.0.1",

Updated:
"@ngx-progressbar/core": "^5.0.1",
"@ngx-progressbar/http": "^5.0.1",

Could you please update the documentation?
