### ISSUE TITLE
progressbar is not hidden on http error

### ISSUE THREAD

**Issue by garcimouche** [MurhafSousli/ngx-progressbar#144]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [X] question
```

### OS and Version?
Linux Ubuntu 16.04
### Versions

Output from: `ng --version` => 1.7.3
output from: `node --version => 8.11.1` , `npm --version => 5.6.0` and Angular =>5.2.9.

### Repro steps
I have configured the progress bar for automatic display on http exchange with:

```
    NgProgressModule.forRoot({color: '#4d148c', spinner: true, spinnerPosition: 'left', thick: false }),
    NgProgressHttpModule

```
It is working fine, except when a Http request fails, the progress bar is still displayed on the screen half way to completion. Is it normal behavior? How can I complete or hide the bar on http error?

Thanks for the module,

### Desired functionality

Hide progressbar on http failure

**Comment by MurhafSousli** [comment]
The progress bar should hide, try the http button in this [stackblitz](https://stackblitz.com/edit/ngx-progressbar-http-cjtkww?file=app/app.component.ts). the http will give 404 error and the progress bar will hide
