### ISSUE TITLE
Progress bar is never completed

### ISSUE THREAD

**Issue by marinesabbah** [MurhafSousli/ngx-progressbar#145]
I work with the version 4.0.1.

I played with your live demo ( https://murhafsousli.github.io/ngx-progressbar/#/) and I notice that your progress bar never reaches the status of ''completed'' unless you click on 'NgProgress. complete()'.

What is the way to access the event ''completed'' without triggering it manually ? 

I try to use it in my project but I have the same issue.

Thank you,

**Comment by MurhafSousli** [comment]
Actually It is working properly, but in the demo there are 2 progress instances. try the [progress http stackblitz](https://stackblitz.com/edit/ngx-progressbar-http) to see it working

**Comment by marinesabbah** [comment]
I try the link you gave me and the result is still the same. I try on Chrome, Firefox and Internet Explorer.

Do you have any idea why it doesn't work ?

**Comment by MurhafSousli** [comment]
Sorry, I didn't understand in the beginning! The progress bar will never reach complete until you call the function complete.
