### ISSUE TITLE
Allow user to configure trickle amount

### ISSUE THREAD

**Issue by jasekiw** [MurhafSousli/ngx-progressbar#146]
The trickle amount is hard coded below.

https://github.com/MurhafSousli/ngx-progressbar/blob/1d0be89237e66fbaac77e724be2192f5f29e9535/lib/core/src/ng-progress-ref.ts#L91-L103

There should be a way to override this with a custom implementation.

Why would someone want to do this? Longer loading tasks are sliding backwards because the trickle has surpassed the actual loading percentage.

**Comment by MurhafSousli** [comment]
@jasekiw There is an input for trickle speed called `[trickleSpeed]`.
While trickling, the trickle amount is hardcoded this way. allowing the user to use custom trickling amounts for different conditions is possible. but how do you think a user would set them?

**Comment by jasekiw** [comment]
@MurhafSousli Sorry for the delay. I meant trickle amount. I accidentally named the issue wrong. 
There are a couple of ways to do this, Using dependency injection you could inject a service which would allow the user to use their own service. A whole service for one method sounds like a lot however.

**Comment by MurhafSousli** [comment]
Setting custom trickling amount can be done like
```ts
NgProgressModule.forRoot({
    trickleFunc: (n: number): number => {
        if (n >= 0 && n < 20) return 10;
        if (n >= 20 && n < 50) return 4;
        if (n >= 50 && n < 80) return 2;
        if (n >= 80 && n < 99) return 0.5;
        return 0;
    }
})
```
or
```html
<ng-progress [trickleFunc]="trickleFunc"></ng-progress>
```
```ts
export class MyComponent {
    trickleFunc = (n: number): number => {
        if (n >= 0 && n < 20) return 10;
        if (n >= 20 && n < 50) return 4;
        if (n >= 50 && n < 80) return 2;
        if (n >= 80 && n < 99) return 0.5;
        return 0;
    }
}
```

**Comment by appl4e** [comment]
I have used trickleFunc exactly as you have mentioned above. But couldn't make it work.
