### ISSUE TITLE
NgProgress.set() not working before execute .start() and .complete()

### ISSUE THREAD

**Issue by stenioanibal** [MurhafSousli/ngx-progressbar#147]
### Bug Report 
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
- [ ] question
```

Hello. I have one static http.get and others are dinamically generated. In first request, i use `NgProgress.start()` and `NgProgress.complete()`.

To other requests (sequentially of this), i use static `.set` method and `.inc` to update the progressbar for each request complete, but, this not working after `NgProgress.complete()`. In your example page, this works beautiful but, in my case, do not.

I make this trick to update really progress in second progressbar load because this not showing really progress in my case, using much concatenated observables of http.get.

Suggestions?

**Comment by MurhafSousli** [comment]
Why not use the [Automagic feature](https://github.com/MurhafSousli/ngx-progressbar#http)?

**Comment by stenioanibal** [comment]
I really thinked and test this very beautiful solution but, in my case this not work like i want. My requests are concatenated in a queue of observables to execute sequentially and, in middle of a first request (static) and others (dynamic) i have an delay without progressbar and, i don't want this. For my case, i thought in following steps:

```
this.ngxProgressbar.start()

-- STATIC HTTP.GET -- 

this.ngxProgressbar.complete()

START FUNCTION TO DYNAMIC GET'S

this.ngxProgressbar.set(0.2)

queueHttps.subscribe(response => {
    this.ngxProgressbar.inc(80 / numOfRequests)

    RESULT OF HTTP REQUEST

    if(isLastHttp){
        this.ngxProgressbar.complete()
    }
});
```

This not work for me. After first `.complete()`, the `.set()` call work but the progressbar won't stop loading to i increment your progress like i want.

This is possible?

**Comment by MurhafSousli** [comment]
I can't understand you. what is happening after you call `.complete` and `.set()`
is trickling, or is it paused? do you want it to trickle or do you want it to pause?

Write it like so in details

**Current behavior:**

**Expected behavior:**

**Comment by stenioanibal** [comment]
**Current behavior:**
After execute `.complete` the `.set` works but the progressbar continue trickling, not stop in value set, for after, i increment using `.inc`.

**Expected behavior:**
After execute `.complete`, stop progressbar in set value and i "manually" increment this a each request complete.

**Comment by MurhafSousli** [comment]
There is a small delay before the progress bar resets after it is completed. if your second http starts immediately, you should either delay manually or start it when the `completed` output emits

 ```
<ng-progress (completed)="getDynamicRequest()"></ng-progress>
```

**Comment by MurhafSousli** [comment]
I am closing this, feel free to continue the discussion

**Comment by cohayfun** [comment]
below the code is works to auto progress start your page. I'm just helping 👍 
if (typeof NProgress != 'undefined') {
$(document).ready(function () {
	NProgress.start();
});
$(window).load(function () {
	//you can change code complete() if well.
	NProgress.done(); 
	});
}

**Comment by cohayfun** [comment]
below the code is works to auto progress start your page. I'm just helping 👍 

if (typeof NProgress != 'undefined') {
		$(document).ready(function () {
			NProgress.start();
		});

		$(window).load(function () {
			NProgress.done();  //you can change code complete() if well.
		});
	}

**Comment by cohayfun** [comment]
Below the code is works to auto progress start your page. I'm just helping 👍 
if (typeof NProgress != 'undefined') {
$(document).ready(function () {
     NProgress.start();
});
$(window).load(function () {
     //you can change code complete() if well.
     NProgress.done(); 
});
}
