### ISSUE TITLE
publish a web component package

### ISSUE THREAD

**Issue by MurhafSousli** [MurhafSousli/ngx-progressbar#154]

**Comment by mmukarram** [comment]
@MurhafSousli, I took a look at your pull request #156. It appears the project structure has been changed (getting rid of some redundant files I suppose). Could you elaborate on this change in the context of _'web component package'_?

**Comment by ggjersund** [comment]
Any progress or estimated time until this will get merged?

**Comment by MurhafSousli** [comment]
I still did not start working on this
