### ISSUE TITLE
Hide existing border css when page loads

### ISSUE THREAD

**Issue by komalg1** [MurhafSousli/ngx-progressbar#159]
How can I hide a top-border css, as it is coinciding with the progress bar?

**Comment by MurhafSousli** [comment]
Which top-border? can you add a screenshot!

**Comment by komalg1** [comment]
![github](https://user-images.githubusercontent.com/29505310/39806186-e77a44e4-5396-11e8-90cc-0862faede33e.png)

Ok so in the screenshot, there is a top red border. When I use a progress-bar, it coincides with that top red bar.. How can I remove the css till the time my http call completes?

**Comment by MurhafSousli** [comment]
That should not happen, you probably have wrong config.. try to reproduce the same in a [stackblitz](https://stackblitz.com/edit/ngx-progressbar) so I can help you

**Comment by komalg1** [comment]
the top red border is my css which has to be there.. But when the page loads, I changed the progress-bar color to blue and I am able to see blue on red.. but it is not looking good. so is there a way in which I could hide the top red border till the time the progress-bar completes ?

**Comment by komalg1** [comment]
Something like this
https://ngx-progressbar-yoyezz.stackblitz.io/

**Comment by MurhafSousli** [comment]
Now I understand. no! I don't think the progress bar is useful in this case, but maybe you can try to set the min value.

`<ng-progress [min]="99"></ng-progress>`
