### ISSUE TITLE
ERROR in Error during template compile of 'CoreModule'   Function calls are not supported in decorators but 'NgProgressModule' was called.

### ISSUE THREAD

**Issue by rintynator** [MurhafSousli/ngx-progressbar#160]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
- [ ] question
```

### Versions
Angular CLI: 6.0.0
Node: 9.4.0
OS: darwin x64
Angular: 6.0.0
... animations, cli, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.6.0
@angular-devkit/build-angular     0.6.0
@angular-devkit/build-optimizer   0.6.0
@angular-devkit/core              0.6.0
@angular-devkit/schematics        0.6.0
@angular/cdk                      6.0.1
@angular/material                 6.0.1
@ngtools/webpack                  6.0.0
@schematics/angular               0.6.0
@schematics/update                0.6.0
rxjs                              6.1.0
typescript                        2.7.2
webpack                           4.6.0

### Error
I got this error in ng build:

ERROR in Error during template compile of 'CoreModule'
  Function calls are not supported in decorators but 'NgProgressModule' was called.

### Question
Is it right, that .done() is now .complete()?

**Comment by MurhafSousli** [comment]
This is not related to this package, it is a bug in Angular 6 https://github.com/angular/angular/issues/23609, when they fix it the error will disappear.

**Comment by iamimbohacker** [comment]
Sorry for spaming here. But can I bypass that issue for prod build?

**Comment by MurhafSousli** [comment]
No, until they fix it. but if you use the source code it will work fine
