### ISSUE TITLE
Issue with rxjs in angular 6

### ISSUE THREAD

**Issue by krishnareddy226** [MurhafSousli/ngx-progressbar#163]
Please update your code to latest angular 6. Rxjs imports are throwing errors.

ERROR in ./node_modules/ngx-progressbar/modules/ngx-progressbar.es5.js
Module not found: Error: Can't resolve 'rxjs/Observable' in '..\node_modules\ngx-progressbar\modules'

node_modules/ngx-progressbar/src/services/progress.service.d.ts(1,10): error TS2305: Module '"../node_modules/rxjs/Subject"' has no exported member 'Subject'.

**Comment by MurhafSousli** [comment]
Please check old issues before submitting a new one
Duplicate #161, #143
