### ISSUE TITLE
Using NgProgressHttpModule and NgProgressRouterModule together

### ISSUE THREAD

**Issue by zzakir** [MurhafSousli/ngx-progressbar#164]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [x] question
```

### OS and Version?

macOS Sierra

### Versions

4.3.0

### Desired functionality

I am trying to user the NgProgressRouterModule and NgProgressHttpModule in tandem. I have a lazy loaded module, whose child route has http calls. So when I used the progress bar, it is completed as soon as the route is loaded and no progress bar is displayed for the http call. Am I doing something wrong?

**Comment by MurhafSousli** [comment]
Are you using lazy load routes? and which want starts the progress bar the http requests or the child navigation?
Can you reproduce in stackblitz?
[router stackblitz](https://stackblitz.com/edit/ngx-progressbar-router), [http stackblitz](https://stackblitz.com/edit/ngx-progressbar-http)

**Comment by zzakir** [comment]
I have reproduced it here: https://stackblitz.com/edit/ngx-progressbar-router-sv3ahh

**Comment by zzakir** [comment]
Fixed it by using just the NgProgressRouterModule and handling the http progress bar manually in the service.

**Comment by shelbincormsquare** [comment]
@zzakir  I'm facing the same issue. Can we do something at root level?
