### ISSUE TITLE
progressbar not working after rendering a new component until page refreshed in angular 6..!!

### ISSUE THREAD

**Issue by farismohammed** [MurhafSousli/ngx-progressbar#173]

**Comment by MurhafSousli** [comment]
Can you create a reproduction [stackblitz](https://stackblitz.com/edit/ngx-progressbar)

**Comment by farismohammed** [comment]
@MurhafSousli when I'm checking in stackblitz, its working fine... but it's not working in my project
i will show you my problem in a gif.

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/11938268/40155476-90dadb64-59b1-11e8-9986-350a0dd4d9de.gif)

**Comment by MurhafSousli** [comment]
In v4.3.0 we added `debounceTime` option  #141, which is useful to not start the progress bar for a small delay, the default value is 0 but it still cause the progress to ignore the very fast requests.

Try to use v4.2.0 and tell me if it fixes the issue

**Comment by farismohammed** [comment]
I'm Still Facing this issue, I' tested in both v4.3.0 and v4.2.0

**Comment by MurhafSousli** [comment]
Did you add the progress bar in the root template? If you can reproduce the issue in a stackblitz. I can look into it

**Comment by farismohammed** [comment]
@MurhafSousli... Yes, it's my fault... am accidentally declaring  <ng-progress> component twice in my project... Sorry..and thank you for great support..!!!
