### ISSUE TITLE
Angular 5, Progress bar in  lazy loaded module - not working

### ISSUE THREAD

**Issue by suparnavg** [MurhafSousli/ngx-progressbar#174]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
- [ ] question
```

### OS and Version?

Windows 10

### Versions

@angular/cli: 1.4.9
node: 6.11.4
os: win32 x64
@angular/animations: 5.2.11
@angular/cli: 1.4.9
@angular/common: 5.2.11
@angular/compiler: 5.2.11
@angular/compiler-cli: 5.2.11
@angular/core: 5.2.11
@angular/forms: 5.2.11
@angular/http: 5.2.11
@angular/platform-browser: 5.2.11
@angular/platform-browser-dynamic: 5.2.11
@angular/platform-server: 5.2.11
@angular/router: 5.2.11
@angular/language-service: 4.2.4
typescript: 2.8.3

### Repro steps

1. Followed the steps given in the router stackblitz: https://stackblitz.com/edit/ngx-progressbar-router
2. Added the ng-progress component below to a component inside my lazy loaded module

<ng-progress #progressBar [min]="0.15" [max]="1"
    [speed]="400" [spinner]="false" [direction]="'leftToRightIncreased'"
    [color]="'#49d1ff'" [trickleSpeed]="250" [thick]="false" [ease]="'linear'"
    ></ng-progress>

### The log given by the failure

Progressbar is not visible.

ERROR TypeError: Object(...) is not a function
    at new NgProgressRef (ngx-progressbar-core.js:27)
    at NgProgress.webpackJsonp.../../../../@ngx-progressbar/core/fesm5/ngx-progressbar-core.js.NgProgress.ref (ngx-progressbar-core.js:281)
    at NgProgressComponent.webpackJsonp.../../../../@ngx-progressbar/core/fesm5/ngx-progressbar-core.js.NgProgressComponent.ngOnInit (ngx-progressbar-core.js:492)
    at checkAndUpdateDirectiveInline (core.js:12411)
    at checkAndUpdateNodeInline (core.js:13935)
    at checkAndUpdateNode (core.js:13878)
    at debugCheckAndUpdateNode (core.js:14771)
    at debugCheckDirectivesFn (core.js:14712)
    at Object.eval [as updateDirectives] (HeaderComponent.html:238)
    at Object.debugUpdateDirectives [as updateDirectives] (core.js:14697)

### Desired functionality

Progressbar should be visible

### Mention any other details that might be useful

The documentation might need to be updated. It says [minimum] and [maximum] are properties of <ng-progress>, using these properties throws an error. Also the router stackblitz lists the properties [min] and [max].

**Comment by MurhafSousli** [comment]
add `NgProgressModule` in your lazy module and it will work

**Comment by suparnavg** [comment]
@MurhafSousli it is already added

**Comment by MurhafSousli** [comment]
Ok then produce the issue in https://stackblitz.com/edit/ngx-progressbar-router and I will look into it.

**Comment by suparnavg** [comment]
Reproduced here: https://stackblitz.com/edit/ngx-progressbar-router-tqkger

I have added the <ng-progress></ng-progress> element to the route-one.component.html and imported  NgProgressModule, NgProgressRouterModule in route-one.module.ts

**Comment by MurhafSousli** [comment]
To use the `NgProgressRouterModule` import it into a root module such as `app.module` The routing progress bar should be in the root template not in a route template
