### ISSUE TITLE
Angular 6 -> HttpClientModule fails

### ISSUE THREAD

**Issue by sergio-new-developer** [MurhafSousli/ngx-progressbar#177]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
- [ ] question
```

### OS and Version?
Windows 10

### Versions
Angular CLI: 6.0.3
Node: 8.11.1
OS: win32 x64
Angular: 6.0.2

### The log given by the failure
_When building/serving app there is error:_

ERROR in node_modules/@ngx-progressbar/http-client/ng-progress.interceptor.d.ts(2,10): error TS2305: Module '"C:/Client/node_modules/rxjs/Observable"' has no exported member 'Observable'.
node_modules/@ngx-progressbar/http-client/node_modules/@ngx-progressbar/core/components/ng-progress-bar/ng-progress-bar.component.d.ts(3,10): error TS2305: Module '"C:/Client/node_modules/rxjs/Observable"' has no exported member 'Observable'.
node_modules/@ngx-progressbar/http-client/node_modules/@ngx-progressbar/core/services/ng-progress.service.d.ts(1,10): error TS2305: Module '"C:/Client/node_modules/rxjs/Subject"' has no exported member 'Subject'.
node_modules/@ngx-progressbar/http-client/node_modules/@ngx-progressbar/core/services/ng-progress.service.d.ts(2,10): error TS2305: Module '"C:/Client/node_modules/rxjs/BehaviorSubject"' has no exported member 'BehaviorSubject'.
node_modules/@ngx-progressbar/http-client/node_modules/@ngx-progressbar/core/services/ng-progress.service.d.ts(3,10): error TS2305: Module '"C:/Client/node_modules/rxjs/Observable"' has no exported member 'Observable'.
node_modules/rxjs/BehaviorSubject.d.ts(1,15): error TS2307: Cannot find module 'rxjs-compat/BehaviorSubject'.
node_modules/rxjs/Observable.d.ts(1,15): error TS2307: Cannot find module 'rxjs-compat/Observable'.
node_modules/rxjs/Subject.d.ts(1,15): error TS2307: Cannot find module 'rxjs-compat/Subject'.

### Desired functionality
it cannot compile http-client module

### Mention any other details that might be useful
Perhaps, this error in Angular changes for rxjs

Hope, you can repair it soon )

**Comment by MurhafSousli** [comment]
Did you import HttpClientModule? you probably did something wrong, look at this [stackblitz](https://stackblitz.com/edit/ngx-progressbar-http)

**Comment by sergio-new-developer** [comment]
course!

Your example includes HttpModule which is deprecated in future angular.
New HttpClientModule is based on RxJS v6

**Comment by MurhafSousli** [comment]
@sergio-new-developer No, we deprecated the usage of HttpModule months ago. This has been discussed in previous issues and the change is mentioned in the changelog. you are using a deprecated package.

For `HttpClientModule` use `NgProgressHttpModule`, Just follow the documentation!
