### ISSUE TITLE
Is it possible to move the progress bar below the navbar?

### ISSUE THREAD

**Issue by rzkhqq** [MurhafSousli/ngx-progressbar#179]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [x ] question
```

### OS and Version?
**Windows 7**

### Versions
Angular CLI: 1.7.4
Node: 8.11.1
OS: win32 x64
Angular: 5.2.10
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

@angular/cli: 1.7.4
@angular-devkit/build-optimizer: 0.3.2
@angular-devkit/core: 0.4.9
@angular-devkit/schematics: 0.3.2
@ngtools/json-schema: 1.2.0
@ngtools/webpack: 1.10.2
@schematics/angular: 0.3.2
@schematics/package-update: 0.3.2
typescript: 2.5.3
webpack: 3.11.0

### Desired functionality
Is it possible to move the progress bar below the navbar?

**Comment by MurhafSousli** [comment]
Yes, have a look at this [stackblitz ](https://stackblitz.com/edit/ngx-progressbar-mutliple-instances)
