### ISSUE TITLE
ProgressBar route doens`t work on angular 5.2

### ISSUE THREAD

**Issue by fernandobd42** [MurhafSousli/ngx-progressbar#180]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
- [ ] question
```

### Versions
Angular CLI: 1.7.4
Node: 9.11.1
OS: darwin x64
Angular: 5.2.11
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router, service-worker

@angular/cdk: 5.0.4
@angular/cli: 1.7.4
@angular/material: 5.0.4
@angular/platform-server: 5.2.0
@angular-devkit/build-optimizer: 0.3.2
@angular-devkit/core: 0.3.2
@angular-devkit/schematics: 0.3.2
@ngtools/json-schema: 1.2.0
@ngtools/webpack: 1.10.2
@schematics/angular: 0.3.2
@schematics/package-update: 0.3.2
typescript: 2.5.3
webpack: 3.11.0

### Repro steps
I follow the documentation steps..

```
....
const options_progress = {
    min: 1,
    max: 100,
    ease: 'linear',
    speed: 200,
    trickleSpeed: 100,
    meteor: true,
    spinner: false,
    direction: 'ltr+' as 'ltr+',
    color: '#264683',
    thick: true
}

@NgModule({
    imports: [
        RouterModule.forChild(NagroRoutes),
        NgProgressModule.forRoot(options_progress),
        NgProgressRouterModule,
        NgProgressHttpModule,
............
```

**Comment by fernandobd42** [comment]
don't have error, only doesn't work

**Comment by fchiumeo** [comment]
this [working](https://stackblitz.com/edit/ngx-progressbar-mutliple-instances-rd1ig1)

**Comment by MurhafSousli** [comment]
@fernandobd42 why do you import NgProgressRouterModule and NgProgressHttpModule in child module?

**Comment by fernandobd42** [comment]
@MurhafSousli because I have 2 core modules at application, each one using the custom colors, so each one I config the specific progressBar options with a specific color..

**Comment by fernandobd42** [comment]
I tried with versions:
    "@ngx-progressbar/core": "^4.3.0",
    "@ngx-progressbar/http": "^5.0.1",
    "@ngx-progressbar/router": "^4.3.0",

and 

    "@ngx-progressbar/core": "^4.1.1",
    "@ngx-progressbar/http": "^5.0.1",
    "@ngx-progressbar/router": "^4.1.1"

............................................................. 

NgProgressRouterModule doest worked at neither one

**Comment by MurhafSousli** [comment]
Currently `NgProgressRouterModule` and `NgProgressHttpModule` cannot be used for mutliple progressbar instances, they are hooked to the `root` progress bar (the one without an id). therefore they should be imported once in the root module.

however, you can change the color of the progress manually using `NgProgress` service
```ts
this.progress.setConfig({ color: 'green'})
``` 
or if you are using a `NgProgressRef`
```ts
this.progressRef.setConfig({ color: 'red'})
```

**Comment by fernandobd42** [comment]
I install the libs

"@ngx-progressbar/core": "^4.0.1",
"@ngx-progressbar/router": "^4.0.1",

config the app.module

const options = {
    min: 1,
    max: 100,
    ease: 'linear',
    speed: 200,
    trickleSpeed: 100,
    meteor: true,
    spinner: false,
    direction: 'ltr+' as 'ltr+',
    color: 'white',
    thick: true
}


NgProgressModule.forRoot(options),
NgProgressRouterModule,

............

and set the 

<ng-progress></ng-progress>
<router-outlet></router-outlet>

but the progress when router change doesn't happen...

**Comment by MurhafSousli** [comment]
This won't help, it can be a problem with your project. try make a reproduction for your issue with this https://stackblitz.com/edit/ngx-progressbar-router-ng5

**Comment by fernandobd42** [comment]
to fix I need to install the exactly versions:

```
"@ngx-progressbar/core": "4.1.1",
"@ngx-progressbar/router": "4.1.1",
```
