### ISSUE TITLE
Angular 5.2.10 - Facing Unexpected token error during runtime

### ISSUE THREAD

**Issue by KaranIsCool** [MurhafSousli/ngx-progressbar#182]
### Bug Report or Feature Request (mark with an `x`)
```
- [X] bug report -> please search issues before submitting
- [ ] feature request
- [ ] question
```

### OS and Version?

Window 10

### Versions

Node ver - 8.11.2
NPM ver - 5.6.0.
I am using VS.NET 2017 for my MVC project which is integrated with the Angular 5.2 version.  

 I am using "@ngx-progressbar/core": "4.0.0" inside the package.json file. 
And this also  "@ngx-progressbar/core": "4.3.0", but still the same error. 

I even tried with @ngx-progressbar/core - 5.0. Please let me know, which is the correct and suitable version for Angular 5.2.

### Repro steps

I followed the steps given in your sample. But i am getting this error from the app module saying 
that 

**(SystemJS) Unexpected token <
	SyntaxError: Unexpected token <
	    at eval (<anonymous>)
	    at Object.eval (http://localhost:55000/Websample/app/app.module.js)**

### Desired functionality

Error: (SystemJS) Unexpected token <
	SyntaxError: Unexpected token <
	    at eval (<anonymous>)

**Comment by MurhafSousli** [comment]
In SystemJS I think you should add the following in `config.js`
```
map: {
  '@ngx-progressbar/core': 'node_modules/ngx-progressbar/bundles/ngx-progressbar-core.umd.js',
}
```

**Comment by KaranIsCool** [comment]
Thanks it worked now. I think you should also mention this config in your documentation for the VS.NET developers. It will help them. 

```
**Package.json** now contains :- 
'@ngx-progressbar/core': '4.3.0',
'@ngx-progressbar/router': '4.3.0'

**Systemjs.config.js** contains:-
 '@ngx-progressbar/core': 'npm:@ngx-progressbar/core/bundles/ngx-progressbar-core.umd.js',
 '@ngx-progressbar/router': 'npm:@ngx-progressbar/router/bundles/ngx-progressbar-router.umd.js'
```
