### ISSUE TITLE
Support -webkit-transform: translate3d for the progress bar

### ISSUE THREAD

**Issue by dodongphure** [MurhafSousli/ngx-progressbar#184]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x] feature request
- [ ] question
```

### OS and Version?

Android 4.4.4 browsers

### Versions

npm@5.6.0
node@8.9.4
angular@5.0.3
ngx-progressbar@4.3.0

### Repro steps

Just do the normal installation steps

### Desired functionality

As I use ngx-progressbar in android browser so it does not support CSS style: **transform: translate3d**.
Could we add style **-webkit-transform: translate3d**

![image](https://user-images.githubusercontent.com/9283980/41138310-aeca564e-6b0a-11e8-8ffe-7fa41452bd32.png)

Thanks!

**Comment by dodongphure** [comment]
Added `[style.webkitTransform]=\"state.transform\"\n` in the template of `ng-progress` then will work.

**Comment by MurhafSousli** [comment]
Sorry I did not get the issue? Do you mean the progress bar is not showing on Android?
the `transform` is pretty well supported https://caniuse.com/#feat=transforms3d

**Comment by dodongphure** [comment]
Yah this issue is this is an android app written in ionic framwork. And when the app runs in android, the progress bar does not show. When debug I see that `transform` is a not know property, but when using `-webkit-transform` instead (as you see in the image) the progress bar can show.
Seem when show the app, phone uses native browser instead, and seem it does not support `transform`.

**Comment by MurhafSousli** [comment]
Safari supports the `transform` property, infact, Angular Material uses only the transform as shown [here](https://github.com/angular/material2/blob/e66df3e45f06c53ccf0adc1bac52c828d3629924/src/lib/progress-bar/progress-bar.ts#L89-L92)
