### ISSUE TITLE
Conflict bug with .done

### ISSUE THREAD

**Issue by embryologist** [MurhafSousli/ngx-progressbar#186]
```
- [x] bug report
- [ ] feature request
- [ ] question
```

### OS and Version?
> .macOS(Sierra)

### Versions
Angular CLI: 6.0.3
Node: 9.11.1
OS: darwin x64
Angular: 6.0.3
npm: 6.1.0

### Repro steps
`npm install --save @ngx-progressbar/core`
`npm install --save @ngx-progressbar/core @ngx-progressbar/http-client`
`npm install --save @ngx-progressbar/core @ngx-progressbar/router`

import { NgProgress } from '@ngx-progressbar/core';

```
export class AppComponent {

  constructor(public progress: NgProgress) {
  }

  ngOnInit(){
    /** progress starts on init */
    this.progress.start();

    setTimeout(() => {
        /** progress ends after 2 seconds */
        this.progress.done();
    }, 2000);
  }
}
```
` <ng-progress></ng-progress>`

### The log given by the failure

> [ts] Property 'done' does not exist on type 'NgProgress'.

The following with Http-client,

> ERROR Error: 1 errors occurred during unsubscription:
>   1) TypeError: _this.progress.done is not a function
>     at new UnsubscriptionError (UnsubscriptionError.js:10)

**ng-progress.service.d.ts**

```
import { NgProgressConfig } from './ng-progress.interface';
export declare class NgProgress {
    /** Stores NgProgressRef instances */
    private readonly _instances;
    /** Global config */
    config: NgProgressConfig;
    constructor(config: NgProgressConfig);
    /**
     * Returns NgProgressRef by ID
     */
    ref(id?: string, config?: NgProgressConfig): any;
    setConfig(config: NgProgressConfig, id?: string): void;
    start(id?: string): void;
    set(n: number, id?: string): void;
    inc(n?: number, id?: string): void;
    complete(id?: string): void;
    isStarted(id?: string): any;
    started(id?: string): any;
    completed(id?: string): any;
    destroy(id?: string): void;
    destroyAll(): void;
}
```

**ngx-progressbar-http-client.js**

  ```
NgProgressInterceptor.prototype.intercept = function(req, next) {
    var _this = this;
    this.inProgressCount++;
    if (!this.progress.isStarted) {
      this.progress.start();
    }
    return next.handle(req).pipe(
      finalize(function() {
        _this.inProgressCount--;
        if (_this.inProgressCount === 0) {
          _this.progress.done();   // here as well.
        }
      }),
    );
  };
```
### Mention any other details that might be useful
Bug fix or am I missing something here? .done does not seem to exist, for some reason router module is working fine. I followed the docs [here](https://github.com/MurhafSousli/ngx-progressbar/blob/master/README_V3.md).

Thank you

**Comment by MurhafSousli** [comment]
You are using the instructions of an older version. please read the docs carefully!
