### ISSUE TITLE
Error when using it on Ionic 3

### ISSUE THREAD

**Issue by jayzyaj** [MurhafSousli/ngx-progressbar#187]
### Bug Report or Feature Request (mark with an `x`)
```
- [X] bug report -> please search issues before submitting
- [ ] feature request
- [ ] question
```

### OS and Version?

```
DISTRIB_ID=LinuxMint
DISTRIB_RELEASE=18.3
DISTRIB_CODENAME=sylvia
DISTRIB_DESCRIPTION="Linux Mint 18.3 Sylvia"
NAME="Linux Mint"
VERSION="18.3 (Sylvia)"
ID=linuxmint
ID_LIKE=ubuntu
PRETTY_NAME="Linux Mint 18.3"
VERSION_ID="18.3"
HOME_URL="http://www.linuxmint.com/"
SUPPORT_URL="http://forums.linuxmint.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/linuxmint/"
VERSION_CODENAME=sylvia
UBUNTU_CODENAME=xenial
cat: /etc/upstream-release: Is a directory
```

### Versions

```
node version: v6.12.2
npm version: 4.6.1

cli packages: (/usr/lib/node_modules)

    @ionic/cli-utils  : 1.19.2
    ionic (Ionic CLI) : 3.20.0

local packages:

    @ionic/app-scripts : 3.1.10
    Ionic Framework    : ionic-angular 3.9.2

System:

    Node : v6.12.2
    npm  : 4.6.1
    OS   : Linux 4.13

Misc:

    backend : pro

```

### Repro steps

I have set up NgProgressRouterModule, NgProgressHttpModule in my **app.module** here is the code below:

```
import { HttpClientModule } from '@angular/common/http';
import { NgProgressModule } from '@ngx-progressbar/core';
import { NgProgressHttpModule } from '@ngx-progressbar/http';
import { GlobalProvider } from '../providers/global';
import { PostApiProvider } from '../providers/post-api';

 imports: [
    BrowserModule,
    HttpClientModule,
    NgProgressModule.forRoot(),
    NgProgressHttpModule,
    IonicModule.forRoot(MyApp)
  ],
```

after that I have an api provider to get all the post from that specific end point and try to get the response in my ionic **homepage** here is the code below:

```
import { PostApiProvider } from './../../providers/post-api';
import { Component } from '@angular/core';
import { NavController } from 'ionic-angular';

@Component({
  selector: 'page-home',
  templateUrl: 'home.html'
})
export class HomePage {

  posts: any = [];

  constructor(
    public navCtrl: NavController,
    private postApiProvider: PostApiProvider
  ) {

  }

  ionViewDidLoad() {
    this.postApiProvider.getAllPost().then(data => {
      this.posts = data;
      console.log(data);
    }).catch(err => console.log(err));
  }

}
```

and here is my code in my Provider below:

```
import { GlobalProvider } from './global';
import { HttpClient } from '@angular/common/http';
import { Injectable } from '@angular/core';

/*
  Generated class for the PostApiProvider provider.

  See https://angular.io/guide/dependency-injection for more info on providers
  and Angular DI.
*/
@Injectable()
export class PostApiProvider {

  constructor(
    public http: HttpClient,
    public global : GlobalProvider
  ) {
    
  }

  getAllPost() {
    return new Promise((resolve, reject) => {
      this.http.get(this.global.baseUrl+'/posts').subscribe(data => {
        console.log(data);
        resolve(data);
      }, err => {
        console.log(err);
      });
    });
  }

}
```

In my **home.html**

```
<ng-progress  color="green"></ng-progress>
<ion-header>
  <ion-navbar>
    <ion-title>Posts</ion-title>
  </ion-navbar>
</ion-header>

<ion-content padding>
  <h2>
    {{ posts.length <= 0 ? "There are no post yet" 
      : posts.length === 1 
        ? "There are 1 post" 
        : "There are " + posts.length + " posts" }}
  </h2>
  <br>
  <ion-list>
    <ion-item-sliding *ngFor="let post of posts; let i = index">
      <ion-item>
        <ion-avatar item-start>
          <img src="">
        </ion-avatar>
        <h2>{{ post.author }}</h2>
        <p>{{ post.title }}</p>
      </ion-item>
      <!-- <ion-item-options side="left">
        <button ion-button color="secondary" (click)="viewForm(post)">
          <ion-icon name="create"></ion-icon>
          Edit
        </button>
      </ion-item-options>
      <ion-item-options side="right">
        <button ion-button color="danger" (click)="deleteConfirm(post.id, i)">
          <ion-icon name="trash"></ion-icon>
          Delete
        </button>
      </ion-item-options> -->
    </ion-item-sliding>
  </ion-list>

  <ion-fab right bottom>
    <button ion-fab color="secondary"><ion-icon name="add"></ion-icon></button>
  </ion-fab>
</ion-content>
```

### The log given by the failure

Here is the complete error log below:

> ERROR Error: Uncaught (in promise): TypeError: Object(...) is not a function
> TypeError: Object(...) is not a function
>     at new NgProgressRef (ngx-progressbar-core.js:27)
>     at NgProgress.ref (ngx-progressbar-core.js:281)
>     at NgProgressComponent.ngOnInit (ngx-progressbar-core.js:492)
>     at checkAndUpdateDirectiveInline (core.js:12411)
>     at checkAndUpdateNodeInline (core.js:13935)
>     at checkAndUpdateNode (core.js:13878)
>     at debugCheckAndUpdateNode (core.js:14771)
>     at debugCheckDirectivesFn (core.js:14712)
>     at Object.eval [as updateDirectives] (HomePage.html:1)
>     at Object.debugUpdateDirectives [as updateDirectives] (core.js:14697)
>     at new NgProgressRef (ngx-progressbar-core.js:27)
>     at NgProgress.ref (ngx-progressbar-core.js:281)
>     at NgProgressComponent.ngOnInit (ngx-progressbar-core.js:492)
>     at checkAndUpdateDirectiveInline (core.js:12411)
>     at checkAndUpdateNodeInline (core.js:13935)
>     at checkAndUpdateNode (core.js:13878)
>     at debugCheckAndUpdateNode (core.js:14771)
>     at debugCheckDirectivesFn (core.js:14712)
>     at Object.eval [as updateDirectives] (HomePage.html:1)
>     at Object.debugUpdateDirectives [as updateDirectives] (core.js:14697)
>     at c (polyfills.js:3)
>     at c (polyfills.js:3)
>     at polyfills.js:3
>     at t.invokeTask (polyfills.js:3)
>     at Object.onInvokeTask (core.js:4751)
>     at t.invokeTask (polyfills.js:3)
>     at r.runTask (polyfills.js:3)
>     at o (polyfills.js:3)

**Comment by MurhafSousli** [comment]
You have 2 options, you either update to Angular 6 which is compatible with Ionic 3, or install the older version of the plugin `v4.3.0`

**Comment by jayzyaj** [comment]
I tried to revert everything to v4.3.0 but does that mean I need to use this since I downgrade the plugin from latest to **4.3.0** I used this [ngx-progressbar-httpclient](https://www.npmjs.com/package/@ngx-progressbar/http-client) and this is the full log of the error below:

> UnsubscriptionError {errors: Array(1), name: "UnsubscriptionError", stack: "UnsubscriptionError: 1 errors occurred during unsu…k (http://localhost:8100/build/vendor.js:5125:33)", message: "1 errors occurred during unsubscription:↵  1) TypeError: _this.progress.done is not a function"}errors: Array(1)0: TypeError: _this.progress.done is not a function
>     at Subscription._unsubscribe (http://localhost:8100/build/vendor.js:134798:32)
>     at Subscription.tryCatcher (http://localhost:8100/build/vendor.js:25123:31)
>     at Subscription.unsubscribe (http://localhost:8100/build/vendor.js:23894:59)
>     at Subscription.tryCatcher (http://localhost:8100/build/vendor.js:25123:31)
>     at FinallySubscriber.Subscription.unsubscribe (http://localhost:8100/build/vendor.js:23907:70)
>     at FinallySubscriber.Subscriber.unsubscribe (http://localhost:8100/build/vendor.js:20472:38)
>     at FinallySubscriber.tryCatcher (http://localhost:8100/build/vendor.js:25123:31)
>     at InnerSubscriber.Subscription.unsubscribe (http://localhost:8100/build/vendor.js:23907:70)
>     at InnerSubscriber.Subscriber.unsubscribe (http://localhost:8100/build/vendor.js:20472:38)
>     at InnerSubscriber._complete (http://localhost:8100/build/vendor.js:124440:14)length: 1__proto__: Array(0)message: "1 errors occurred during unsubscription:↵  1) TypeError: _this.progress.done is not a function"name: "UnsubscriptionError"stack: "UnsubscriptionError: 1 errors occurred during unsubscription:↵  1) TypeError: _this.progress.done is not a function↵    at new UnsubscriptionError (http://localhost:8100/build/vendor.js:124394:25)↵    at InnerSubscriber.Subscription.unsubscribe (http://localhost:8100/build/vendor.js:23923:19)↵    at InnerSubscriber.Subscriber.unsubscribe (http://localhost:8100/build/vendor.js:20472:38)↵    at InnerSubscriber._complete (http://localhost:8100/build/vendor.js:124440:14)↵    at InnerSubscriber.Subscriber.complete (http://localhost:8100/build/vendor.js:20464:18)↵    at FinallySubscriber.Subscriber._complete (http://localhost:8100/build/vendor.js:20482:26)↵    at FinallySubscriber.Subscriber.complete (http://localhost:8100/build/vendor.js:20464:18)↵    at XMLHttpRequest.onLoad (http://localhost:8100/build/vendor.js:57674:30)↵    at t.invokeTask (http://localhost:8100/build/polyfills.js:3:15660)↵    at Object.onInvokeTask (http://localhost:8100/build/vendor.js:5125:33)"__proto__: Error
> (anonymous) @ ion-dev.js?v=3.1.9:156
> defaultErrorLogger @ core.js:1449
> ErrorHandler.handleError @ core.js:1510
> IonicErrorHandler.handleError @ ionic-error-handler.js:61
> next @ core.js:5508
> schedulerFn @ core.js:4342
> SafeSubscriber.__tryOrUnsub @ Subscriber.js:242
> SafeSubscriber.next @ Subscriber.js:189
> Subscriber._next @ Subscriber.js:129
> Subscriber.next @ Subscriber.js:93
> Subject.next @ Subject.js:55
> EventEmitter.emit @ core.js:4322
> (anonymous) @ core.js:4782
> t.invoke @ polyfills.js:3
> r.run @ polyfills.js:3
> NgZone.runOutsideAngular @ core.js:4708
> onHandleError @ core.js:4782
> t.handleError @ polyfills.js:3
> r.runTask @ polyfills.js:3
> e.invokeTask @ polyfills.js:3
> p @ polyfills.js:2
> v @ polyfills.js:2
> error (async)
> O @ polyfills.js:2
> t.scheduleTask @ polyfills.js:3
> r.scheduleTask @ polyfills.js:3
> r.scheduleEventTask @ polyfills.js:3
> (anonymous) @ polyfills.js:2
> r.set @ polyfills.js:2
> exports.Connector.Connector.connect @ livereload.js?snipver=1:92
> Connector @ livereload.js?snipver=1:60
> LiveReload @ livereload.js?snipver=1:330
> (anonymous) @ livereload.js?snipver=1:1132
> 8../customevents @ livereload.js?snipver=1:1158
> s @ livereload.js?snipver=1:1
> e @ livereload.js?snipver=1:1
> (anonymous) @ livereload.js?snipver=1:1
>

**Comment by MurhafSousli** [comment]
Where did you read `ngx-progressbar-httpclient`? that package was deprecated a year ago.
Use `@ngx-progressbar/http` for HttpClient requests
