### ISSUE TITLE
Hangs at 30 percent when using inside ngxs action

### ISSUE THREAD

**Issue by msegmx** [MurhafSousli/ngx-progressbar#188]
Hi,
Thanks for a great plugin !

But I have a problem : 

ngx-progressbar works fine when http calls are made from within a service or resolver.
But when the http request is started from within an NGXS action, the progress bar hangs around 30%, for every request.
I can see that the http request finishes and the data is displayed on the screen, but the progress bar is still hung at 30 %.

Please note that, when the progress bar is hung, a simple resize of the browser window makes the progress bar and the spinning circle in the upper right corner disappear; the progress bar doesn't go complete, but simply disappears.

What can I do to debug ngx-progressbar and find the culprit ?

I want to ask the ngxs team as well, but could you please give some information that would narrow down the culprit ?

**Comment by MurhafSousli** [comment]
@msegmx Hi! First of all thanks!

But you need to fill the required info in the issue template. Inlcude the versions for the record. As the plugin gets updated, we cannot remember which version had the issue.

The best way is to find the culprit is to reproduce the issue in a [stackblitz](https://stackblitz.com/edit/ngx-progressbar).

**Comment by msegmx** [comment]
Sorry, my bad. Here it is. I've also created a stackblitz, as requested.

### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
- [ ] question
```

### OS and Version?


### Versions
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/


Angular CLI: 6.0.0
Node: 10.0.0
OS: linux x64
Angular: 6.0.0
... animations, cli, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.6.0
@angular-devkit/build-angular     0.6.0
@angular-devkit/build-optimizer   0.6.0
@angular-devkit/core              0.6.0
@angular-devkit/schematics        0.6.0
@angular/cdk                      5.2.5
@ngtools/webpack                  6.0.0
@schematics/angular               0.6.0
@schematics/update                0.6.0
rxjs                              6.1.0
typescript                        2.7.2
webpack                           4.6.0



### Repro steps
https://stackblitz.com/edit/ngx-progressbar-bat5zp?file=src%2Fapp%2Fapp.module.ts
https://ngx-progressbar-bat5zp.stackblitz.io

I've added a "Make request" button. If clicked the progress bar hangs at 20%.

Please note, in browser console, you can see that the data arrives and is printed to console.

### The log given by the failure
no log available. progress bar doesn't finish. 


### Desired functionality
ProgressBar should finish, but it hangs at around 30%.

**Comment by MurhafSousli** [comment]
It is very strange, the progress bar is no showing at all on my end.. but the progress state is working properly and `(started)` and `(completed)` outputs emits properly with the HTTP request.

It is a rendering issue, a change detection issue to be more specific.

I am not sure what is the cause! but I can guess that ngxs is running the HTTP request outside angular zone which cause the change detection to turn off.

Can you report that to confirm on their repo

Check the console in this [stackblitz](https://stackblitz.com/edit/ngx-progressbar-9acrrq?file=src%2Fapp%2Fapp.component.ts)

**Comment by MurhafSousli** [comment]
@msegmx Yea as I expected, it is the `zone.runOutsideAngular` used in ngxs that is causing the issue

It works when your wrap the HTTP request within angular zone
```ts
export class TestUrlState {

  constructor(private http: HttpClient, private zone: NgZone) { }

  @Action(LoadUrl)
  load({ setState }: StateContext<string>) {

    this.zone.run(() => {

      this.http.get<any>('https://reqres.in/api/users?delay=2').pipe(
        tap(res => console.log(res))
      ).subscribe();

    });
  }
}
```
I am not sure if this works for you, but here is the fixed [stackblitz](https://stackblitz.com/edit/ngx-progressbar-83snxj?file=src/app/ngxs.ts). 

I don't think we can do much about it here, but this should be reported to ngxs repo.
