### ISSUE TITLE
Version, which supports both '@angular/http' and @angular/common/http 

### ISSUE THREAD

**Issue by basileos** [MurhafSousli/ngx-progressbar#193]
### Bug Report or Feature Request (mark with an `x`)
```
- [] bug report -> please search issues before submitting
- [ ] feature request
- [x] question
```

### OS and Version?
Ubuntu 14.04

### Versions
Angular CLI: 1.6.6
Node: 8.11.1
OS: linux x64
Angular: 5.2.2
... common, compiler, compiler-cli, core, forms, http
... platform-browser, platform-browser-dynamic, router

@angular/cli: 1.6.6
@angular-devkit/build-optimizer: 0.0.42
@angular-devkit/core: 0.0.29
@angular-devkit/schematics: 0.0.52
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.9.6
@schematics/angular: 0.1.17
typescript: 2.5.3
webpack: 3.10.0

### Repro steps

https://stackblitz.com/edit/ngx-progressbar-http-enpg2h

### Desired functionality

SInce i have many places in legacy code, where deprecated  '@angular/http' is used and '@angular/common/http' in recent code , i'm curious if exists ngx-progressbar version, which supports both versions of angular Http libs, because version 4.3.0 doesnt work for  '@angular/http'

**Comment by MurhafSousli** [comment]
The last version that has support for `@angular/http` is [v3.0.2](https://github.com/MurhafSousli/ngx-progressbar/blob/master/CHANGELOG.md#302), [documentations](https://github.com/MurhafSousli/ngx-progressbar/blob/master/README_V3.md)
