### ISSUE TITLE
ngx-progressbar not compatible with the rxjs 6

### ISSUE THREAD

**Issue by sunny701** [MurhafSousli/ngx-progressbar#194]
ngx-progressbar not compatible with the rxjs 6, giving below errors, pl resolve it.

- ERROR in ./node_modules/ngx-progressbar/modules/ngx-progressbar.es5.js Module not found: Error: Can't resolve 'rxjs/BehaviorSubject'
- ERROR in ./node_modules/ngx-progressbar/modules/ngx-progressbar.es5.js Module not found: Error: Can't resolve 'rxjs/Observable' 
- ERROR in ./node_modules/ngx-progressbar/modules/ngx-progressbar.es5.js Module not found: Error: Can't resolve 'rxjs/Subject'
- ERROR in ./node_modules/ngx-progressbar/modules/ngx-progressbar.es5.js Module not found: Error: Can't resolve 'rxjs/add/observable/timer'
- ERROR in ./node_modules/ngx-progressbar/modules/ngx-progressbar.es5.js Module not found: Error: Can't resolve 'rxjs/add/operator/do' 
- ERROR in ./node_modules/ngx-progressbar/modules/ngx-progressbar.es5.js Module not found: Error: Can't resolve 'rxjs/add/operator/finally 
- ERROR in ./node_modules/ngx-progressbar/modules/ngx-progressbar.es5.js Module not found: Error: Can't resolve 'rxjs/add/operator/switchMap
- ERROR in ./node_modules/ngx-progressbar/modules/ngx-progressbar.es5.js Module not found: Error: Can't resolve 'rxjs/add/operator/takeWhile'

**Comment by fchiumeo** [comment]
ngx-progressbar is old version you need @ngx-progressbar/core

PD: https://github.com/MurhafSousli/ngx-progressbar/blob/master/README_V3.md
