### ISSUE TITLE
"export 'defineInjectable' was not found in '@angular/core'

### ISSUE THREAD

**Issue by dhaniksahni** [MurhafSousli/ngx-progressbar#210]
getting below error on running application. i am using angular 6 - @angular/cli -6.2.1,

WARNING in ./node_modules/@ngx-progressbar/core/fesm5/ngx-progressbar-core.js 436:52-68
"export 'defineInjectable' was not found in '@angular/core'

WARNING in ./node_modules/@ngx-progressbar/core/fesm5/ngx-progressbar-core.js 436:134-140
"export 'inject' was not found in '@angular/core'
i ｢wdm｣: Compiled with warnings.

**Comment by apellicc** [comment]
hello, I have the same problem with angular 5.2.8 and angular-cli 1.7.3

**Comment by jojoaddison** [comment]
Hi @MurhafSousli,
Am seeing the same warnings with angular 5.2.0 and angular/cli 1.6.6
Any ideas what can be done?
Thanks.

**Comment by MurhafSousli** [comment]
Ofcourse, either add rxj-compat `npm i rxjs-compat` or downgrade to v4.3.0
