### ISSUE TITLE
Handling CanActivate/CanDeactivate

### ISSUE THREAD

**Issue by swymmwys** [MurhafSousli/ngx-progressbar#211]
### Feature Request 
```
- [x] feature request
```

### Repro steps
Use CanActivate/CanDeactivate guards on any route.
Progress bar appears when resolving guard.

### Desired functionality
It would be nice to have an ability to define whether you need or don't need to show progress bar while resolving CanActivate/CanDeactivate guards.
It's helpful when user have an unsaved changes and you are showing modal dialog, where he can chose to stay on current page or go to other and discard changes.
For now, when I show modal dialog from CanActivate/CanDeactivate guard, progress bar is shows up, which is unnecessary for that moment.

**Comment by MurhafSousli** [comment]
@swymmwys can you add reproduction?

**Comment by swymmwys** [comment]
@MurhafSousli please see https://stackblitz.com/edit/angular-candeactivate-8vvebg
On CompnentB we have a canDeactivate guard which delay route change for two seconds.
My idea is to have an ability to configure this behaviour. Because in case if we are showing modal dialog in canDeactivate guard, we don't want to show progress bar until user will click button which perform either a redirect to another page or stay on current.

**Comment by MurhafSousli** [comment]
The router feature works when [router events](https://angular.io/api/router/Event) emits a `NavigationStart` 
We can add a feature to choose on which router event type you want to start the progress

**Comment by swymmwys** [comment]
yes, that is I'm talking about.
