### ISSUE TITLE
ngx-progressbar not showing after updating angular and rxjs

### ISSUE THREAD

**Issue by mhand7** [MurhafSousli/ngx-progressbar#213]
### Bug Report or Feature Request (mark with an `x`)
```
- [X] bug report -> please search issues before submitting
- [ ] feature request
- [ ] question
```

### Versions

Angular CLI: 7.0.0-rc.1
Node: 9.3.0
OS: win32 x64
Angular: 6.1.9

### Repro steps

The progress bar was working fine before updating, but after updating the libraries, it stopped showing in the top of the screen whenever I call the server

### The log given by the failure

No Errors

**Comment by omahjoub** [comment]
Had the same issue @MurhafSousli

**Comment by lycwed** [comment]
Had the same issue @MurhafSousli

**Comment by George35mk** [comment]
Had the same issue @MurhafSousli :)

**Comment by Ellundril** [comment]
Hi,
Had the same issue @MurhafSousli :)

**Comment by MurhafSousli** [comment]
I have not touched angular 7 yet, if anyone interested in fixing this, please submit a PR or just tell me what is breaking it

**Comment by omahjoub** [comment]
I think it's not really an issue, i changed my import from `NgProgressHttpModule` to `NgProgressHttpModule.forRoot()` and it worked like a charm on Angular `6.1.X` and `7.0.0.RCX`.
Hope this helps.

**Comment by greatsayan** [comment]
Hi,
I'm currently trying to use this plugin but I'm facing some problems.
I'm using a Shared module (which contain my services and other stuff) so I imported NgProgressHttpModule and NgProgressModule in my shared module and I put the "ng-progess" template in my app.component inside a subModule but the progress bar is not showing at all when I made a request.

I'm not sure to understand what I need to do for that...

Share Module:
@NgModule({
    imports: [
        HttpClientModule,
        NgProgressModule.forRoot({
            spinnerPosition: 'left',
            color: '#f71cff',
            thick: true
        }),
        NgProgressHttpModule.forRoot()
    ],
    declarations: [
        SharedComponent, customPipes etc...
    ],
    exports: [
        SharedFooterComponent, ModalComponent, BinNumberFormat, TelFormat, Capitalize, PagerComponent
    ]
})
export class SharedModule {
    static forRoot(): ModuleWithProviders {
        return {
            ngModule: SharedModule,
            providers: [
                Services...
            ]
        };
    }
}

My SubModule
@NgModule({
    imports: [
        SharedModule.forRoot(), NgProgressModule
    ],

    declarations: [AppComponent],

    exports: [],

    bootstrap: [AppComponent],

    providers: [
        {
            provide: Http,
            useFactory: httpFactory,
            deps: [XHRBackend, RequestOptions]
        }
    ]
})
Can someone help me please?

**Comment by MurhafSousli** [comment]
@omahjoub Thanks for your feedback, This change is mentioned in [CHANGELOG](https://github.com/MurhafSousli/ngx-progressbar/blob/master/CHANGELOG.md#510) for v5.1.0

**Comment by MurhafSousli** [comment]
@greatsayan 

### Rule No.1: Never import any module with `forRoot()` in your `SharedModule`
Follow the documentation, import the modules with `forRoot()` in your root module only. do not import `NgProgressHttpModule` or `NgProgressRouterModule` anywhere else!

In the shared module just import the `NgProgressModule` without `forRoot()`, 

> **Note** that `NgProgressHttpModule` is used for `HttpClientModule`, this plugin do not support the deprecated `HttpModule`
