### ISSUE TITLE
`silentApis` not working in production build (using ssr)

### ISSUE THREAD

**Issue by muizabdul29** [MurhafSousli/ngx-progressbar#216]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
- [ ] question
```

### OS and Version?

macOS High Sierra 10.13.6

### Versions

@angular-devkit/architect         0.6.8
@angular-devkit/build-angular     0.6.8
@angular-devkit/build-optimizer   0.6.8
@angular-devkit/core              0.6.8
@angular-devkit/schematics        0.8.4
@angular/cli                      6.2.4
@ngtools/webpack                  6.0.8
@schematics/angular               0.8.4
@schematics/update                0.8.4
rxjs                              6.3.3
typescript                        2.9.2
webpack                           4.8.3

### Repro steps

Register Http module in app root.

```
@NgModule({
    imports: [
        BrowserModule.withServerTransition({ appId: 'main' }),
        TransferHttpCacheModule,
        CoreModule,
        AppRoutingModule,
        NgProgressModule.forRoot(),
        NgProgressHttpModule.forRoot({
            silentApis: ['replies'].map(
                u => `${environment.apiUrl}/${u}`
            )
        })
    ],
    declarations: [AppComponent],
    bootstrap: [AppComponent]
})
export class AppModule {}
```

### The log given by the failure

None.

### Desired functionality

It should work the same as it is supposed to (as described in wiki).

### Mention any other details that might be useful

It is working fine in development mode i.e. it ignores the specified api urls, but does not work in production build when using ssr. I inserted console.log inside .map to debug this.

```
        NgProgressHttpModule.forRoot({
            silentApis: ['replies'].map(u => {
                console.log(environment.apiUrl);
                return `${environment.apiUrl}/${u}`;
            })
        })
```

It was ignored when using production build but worked fine in development mode.

**Comment by MurhafSousli** [comment]
@muizabdul29 Did you try it without `[replies].map`? try it with just `['/replies']` instead

**Comment by muizabdul29** [comment]
Yes, I did in the beginning. But it wasn't working for development mode as well. I did some digging and found out that it was using `.startWith()` method to filter out the urls so I appended the base API url and it worked fine in the development mode.

**Comment by muizabdul29** [comment]
If you think that this issue is not exactly related to the package, feel free to close this. I do have a working workaround i.e. to manually start and complete the progress bar on desired http calls.

**Comment by muizabdul29** [comment]
Yes, that is what I thought but I have made it working now. I did string concatenation inside array and it works. Well, this was never a problem with your package. Sorry about that.

```
        NgProgressHttpModule.forRoot({
            silentApis: [environment.apiUrl + '/replies']
        })
```
