### ISSUE TITLE
ngx-progressbar not working on load children module

### ISSUE THREAD

**Issue by hoainhan** [MurhafSousli/ngx-progressbar#218]
Hi all.
I have a problem with ngx-progressbar
I use multi module for lazy loading, and I apply ngx-progressbar.
It is working on dashboard page, but all child page in it then not working.
Please help me , many thank.

**Comment by MurhafSousli** [comment]
You should fill the template issue with the required info first

**Comment by andrefarzat** [comment]
@hoainhan I've faced the same issue. I've found this thread on angular's repo: https://github.com/angular/angular/issues/20575
Fixed my issue importing `HttpClientModule` only at the root level (i.e.: only on `app.module`).
Hope it helps
