### ISSUE TITLE
Angular 7 - Cannot build aot

### ISSUE THREAD

**Issue by ErwSim** [MurhafSousli/ngx-progressbar#219]
### Bug Report or Feature Request (mark with an `x`)
```
- [ X] bug report -> please search issues before submitting
- [ ] feature request
- [ ] question
```

### OS and Version?
Linux Debian Stretch

### Versions
Angular CLI: 7.0.1
Node: 8.12.0
OS: linux x64
Angular: 7.0.0
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router, service-worker

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.10.1
@angular-devkit/build-angular     0.10.1
@angular-devkit/build-optimizer   0.10.1
@angular-devkit/build-webpack     0.10.1
@angular-devkit/core              0.7.5
@angular-devkit/schematics        7.0.1
@angular/cdk                      6.4.7
@angular/cli                      7.0.1
@angular/material                 6.4.7
@angular/pwa                      0.7.5
@ngtools/webpack                  7.0.1
@schematics/angular               7.0.1
@schematics/update                0.10.1
rxjs                              6.3.3
typescript                        3.1.3
webpack                           4.19.1

### Repro steps
Build the project aot with angular 7

### The log given by the failure
ERROR in : Template parse errors:
The pipe 'async' could not be found ("
    <ng-container [ERROR ->]*ngIf="state$ | async; let state">
      <div class="ng-progress-bar"
            [class.-active]="st"): /drone/src/192.168.100.10/Intranet/Intranet/node_modules/@ngx-progressbar/core/ngx-progressbar-core.d.ts.NgProgressComponent.html@1:18

**Comment by fchiumeo** [comment]
it's enableIvy: true ?
see [angular issue](https://github.com/angular/angular/issues/26436)

**Comment by ErwSim** [comment]
Yes, that was the issue
I disabled ivy and now it works

Sorry for the mistake and thank you :)
