### ISSUE TITLE
Update to Angular 7.0

### ISSUE THREAD

**Issue by mhosman** [MurhafSousli/ngx-progressbar#220]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x] feature request
- [ ] question
```

**Comment by msegmx** [comment]
Note : After upgrading to Angular 7 I get "Property 'start' does not exist on type 'NgProgress'" as error.

**Comment by MurhafSousli** [comment]
It seems to be working fine! https://stackblitz.com/edit/ngx-progressbar

**Comment by msegmx** [comment]
Hi Murhaf,

thanks for great and quick support !

I get a compile time error here :

[https://stackblitz.com/edit/ngx-progressbar-dn8dsu?file=src%2Fapp%2Fapp.component.ts](https://stackblitz.com/edit/ngx-progressbar-dn8dsu?file=src%2Fapp%2Fapp.component.ts)

Can you look at it ?

**Comment by MurhafSousli** [comment]
Check the [changelog](https://github.com/MurhafSousli/ngx-progressbar/blob/master/CHANGELOG.md#520) for the recent version, you need to the `progressRef` to start the progress

```ts
startLoading() {
  this.progress.ref().start();
}
```

**Comment by mhosman** [comment]
It's working but you get this message:

```
npm WARN @ngx-progressbar/core@5.2.0 requires a peer of @angular/common@^6.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN @ngx-progressbar/core@5.2.0 requires a peer of @angular/core@^6.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN @ngx-progressbar/http@5.2.0 requires a peer of @angular/common@^6.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN @ngx-progressbar/http@5.2.0 requires a peer of @angular/core@^6.0.0 but none is installed. You must install peer dependencies yourself.
```
