### ISSUE TITLE
 change the id of the http interceptor progress bar dynamically

### ISSUE THREAD

**Issue by ThisNetWorks** [MurhafSousli/ngx-progressbar#222]
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [x] question
```

### Desired functionality

When using the http and router interceptor is it possible to change the id of the progress bar dynamically after importing with NgProgressHttpModule.forRoot()?

The use case is dialog boxes which make http calls.

**Comment by MurhafSousli** [comment]
Changing the id dynamically is not possible, but you set the dialog progressbar to the http progressRef id
