### ISSUE TITLE
Error using multiple progressbars without ID in seperate template header files

### ISSUE THREAD

**Issue by ggjersund** [MurhafSousli/ngx-progressbar#223]
### Bug Report or Feature Request (mark with an `x`)
```
- [X] bug report -> please search issues before submitting
- [ ] feature request
- [ ] question
```

### OS and Version?

MacOS Mojave

### Versions

```
@angular-devkit/architect         0.8.5
@angular-devkit/build-angular     0.8.5
@angular-devkit/build-optimizer   0.8.5
@angular-devkit/build-webpack     0.8.5
@angular-devkit/core              0.8.5
@angular-devkit/schematics        0.8.5
@angular/cli                      6.2.5

@ngtools/webpack                  6.2.5
@schematics/angular               0.8.5
@schematics/update                0.8.5
rxjs                              6.2.2
typescript                        2.9.2
webpack                           4.20.2
```

### Repro steps

Create two modules each a lazy loaded child of the root module. Each child module has a template containing `<ng-progress></ng-progress>`, but they belong to different Routes trees. Aka. root module `www.example.com`, module 1: `www.example.com/module1`, module 2: `www.example.com/module2`.
Even though they dont import each other the progress bar breaks when transitioning between them.
I have tried only using the progress bar in the root module and it works fine then.

### The log given by the failure

No error log, just stops working.

### Desired functionality

Being able to use multiple ng progressbars with id as root, as long as they are not in the same module (or even better, being able to have multiple root ng progress bars). In my case I have different features that require different headers, which again results in different location requirements for my loader.

**Comment by MurhafSousli** [comment]
The progress bar creates `NgProgressRef` on init and destroys it on `ngOnDestroy`

https://github.com/MurhafSousli/ngx-progressbar/blob/f6ec80dcd92047553044f95cbd359e00626e5416/projects/core/src/lib/ng-progress.component.ts#L133-L139

It should be initialized again.. but maybe the progress bar in the `module1` is being destroyed after the new progress bar in `module2` has initialized.

In anyway, you should place that progress bar in the root module
