### ISSUE TITLE
Migrated to @ngx-progressbar/core from ngx-progressbar

### ISSUE THREAD

**Issue by sureshabbi2** [MurhafSousli/ngx-progressbar#227]
Hi, 
I have migrated the ngx-progressbar to @ngx-progressbar/core.

I am getting the UI spinner while loading the component/module. But for HTTP requests, the spinner is not getting displayed.

These are the modules, we have used and imported into our application.
NgProgressModule.forRoot(),
    NgProgressHttpModule.forRoot(),
    NgProgressRouterModule.forRoot() 

Can you please help me.

Thanks,
Suresh.

**Comment by MurhafSousli** [comment]
Please add a reproduction to your issue
