### ISSUE TITLE
Cannot use it in component anymore in Angular 7

### ISSUE THREAD

**Issue by lahode** [MurhafSousli/ngx-progressbar#228]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
- [ ] question
```

### OS and Version?
Mac OSX El Capitan

### Versions
Angular 7

### Repro steps
import { NgProgress } from '@ngx-progressbar/core';

  constructor(private readonly _progress: NgProgress) {}

ngOnInit() {
    this.storeLoadingSubscription = this._store.select(state => state.loading)
      .subscribe(loading => {
        if (loading.length > 0) {
          this._progress.start();
        } else {
          this._progress.destroy();
        }
      });
}

### The log given by the failure
_this._progress.start is not a function
_this._progress.destroy is not a function

### Desired functionality
Make it work again please as it used to.

**Comment by fchiumeo** [comment]
see https://github.com/MurhafSousli/ngx-progressbar/blob/master/CHANGELOG.md#breaking-changes
