### ISSUE TITLE
Outdated NPM package

### ISSUE THREAD

**Issue by jandeu** [MurhafSousli/ngx-progressbar#231]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [x] question
```

### OS and Version?
Windows 10

### Versions
```
Angular CLI: 6.2.1
Node: 8.10.0
OS: win32 x64
Angular: 6.1.7
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.6.8
@angular-devkit/build-angular     0.6.8
@angular-devkit/build-optimizer   0.6.8
@angular-devkit/core              0.6.8
@angular-devkit/schematics        0.8.1
@angular/cli                      6.2.1
@ngtools/webpack                  6.0.8
@schematics/angular               0.8.1
@schematics/update                0.8.1
rxjs                              6.3.3
typescript                        2.9.2
webpack                           4.8.3
```

### Desired functionality
Last published version on NPM is 2.1.1 [https://www.npmjs.com/package/ngx-progressbar](https://www.npmjs.com/package/ngx-progressbar) I would like to use this library, but the version on NPM is not compatible with `rxjs ^6.0.0` and I would prefer not to have dependency on `rxjs-compact`. Am I looking at wrong package? Latest version seems to be v5.2.0

**Comment by MurhafSousli** [comment]
Where did you find `ngx-progressbar` in the docs? That package was deprecated years ago! It is `@ngx-progressbar/core`
