### ISSUE TITLE
Override/Replace NgProgressInterceptor 

### ISSUE THREAD

**Issue by aikrez** [MurhafSousli/ngx-progressbar#234]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [X] question
```

### OS and Version?

> Windows 10.

### Versions

  "@ngx-progressbar/core": "5.0.1",
    "@ngx-progressbar/http": "5.0.1",
    "@ngx-progressbar/router": "5.0.1",

Angular CLI: 6.2.5
Node: 8.11.3
OS: win32 x64
Angular: 6.1.10
... common, compiler, compiler-cli, core, forms, http
... platform-browser, platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.8.5
@angular-devkit/build-angular     0.8.5
@angular-devkit/build-optimizer   0.8.5
@angular-devkit/build-webpack     0.8.5
@angular-devkit/core              0.8.5
@angular-devkit/schematics        0.8.5
@angular/animations               6.1.6
@angular/cdk                      6.4.7
@angular/cli                      6.2.5
@angular/material                 6.4.7
@ngtools/webpack                  6.2.5
@schematics/angular               0.8.5
@schematics/update                0.8.5
rxjs                              6.2.0
typescript                        2.9.2
webpack                           4.17.1

### The log given by the failure

> error TS2305: Module '"xx/node_modules/@ngx-progressbar/http/ngx-progressbar-http"' has no exported member 'NgProgressInterceptor'.

### Desired functionality

How can I override the NgProgressInterceptor? The import cannot be resolved

`import { NgProgressInterceptor } from '@ngx-progressbar/http';`

`
providers:[
...
   { provide: NgProgressInterceptor , useClass: CustomProgressInterceptor}
]
`

### Mention any other details that might be useful

I want to add a feature to the custom interceptor so it does not intercept when a certain header is present in the request. Currently only configuration of silentApis is provided.

**Comment by MurhafSousli** [comment]
@aikrez You cannot replace an interceptor, you can remove `@ngx-progressbar/http` as @sndpkpr suggested and provide your own interceptor.

I will add this as a feature in future release

**Comment by elega9t** [comment]
I am still getting 'NgProgressInterceptor' was not found in '@ngx-progressbar/http' with

"@ngx-progressbar/core": "^5.3.2",
"@ngx-progressbar/http": "^5.3.2"

Am I missing something?
