### ISSUE TITLE
Progress bar not working for Angular 6

### ISSUE THREAD

**Issue by chr1soscl** [MurhafSousli/ngx-progressbar#235]
Trying to use the progress bar for an Angular 6 project but it gives an error about observable, should I install another version? currently I had installed 2.1.1

 "dependencies": {
    "@angular/animations": "^6.1.0",
    "@angular/cdk": "^6.2.0",
    "@angular/common": "^6.1.0",
    "@angular/compiler": "^6.1.0",
    "@angular/core": "^6.1.0",
    "@angular/forms": "^6.1.0",
    "@angular/http": "^6.1.0",
    "@angular/material": "^6.4.6",
    "@angular/platform-browser": "^6.1.0",
    "@angular/platform-browser-dynamic": "^6.1.0",
    "@angular/router": "^6.1.0",
    "@auth0/angular-jwt": "^2.0.0",
    "bootstrap": "^4.1.3",
    "core-js": "^2.5.4",
    "grunt-war": "^0.5.1",
    "jquery": "^3.3.1",
    "ngx-progressbar": "^2.1.1",
    "popper.js": "^1.14.4",
    "rxjs": "^6.0.0",
    "zone.js": "~0.8.26"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.7.0",
    "@angular-devkit/build-ng-packagr": "~0.7.0",
    "@angular/cli": "~6.1.1",
    "@angular/compiler-cli": "^6.1.0",
    "@angular/language-service": "^6.1.0",
    "@types/jasmine": "~2.8.6",
    "@types/jasminewd2": "~2.0.3",
    "@types/node": "~8.9.4",
    "codelyzer": "~4.2.1",
    "grunt": "^1.0.3",
    "jasmine-core": "~2.99.1",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~1.7.1",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "~2.0.0",
    "karma-jasmine": "~1.1.1",
    "karma-jasmine-html-reporter": "^0.2.2",
    "ng-packagr": "^3.0.0",
    "protractor": "~5.3.0",
    "ts-node": "~5.0.1",
    "tsickle": ">=0.29.0",
    "tslib": "^1.9.0",
    "tslint": "~5.9.1",
    "typescript": "~2.7.2"
  }

ERROR in node_modules/ngx-progressbar/src/services/interceptor.provider.d.ts(2,10): error TS2305: Module
'"C:/Users/code/Project/node_modules/rxjs/Observable"' has no exported member 'Observable'.
node_modules/ngx-progressbar/src/services/progress.service.d.ts(1,10): error TS2305: Module '"C:/Users/code/Project/node_modules/rxjs/Subject"' has no exported member 'Subject'.
node_modules/ngx-progressbar/src/services/progress.service.d.ts(3,10): error TS2305: Module '"C:/Users/code/Project/node_modules/rxjs/BehaviorSubject"' has no exported member 'BehaviorSubject'.
node_modules/rxjs/BehaviorSubject.d.ts(1,15): error TS2307: Cannot find module 'rxjs-compat/BehaviorSubject'.
node_modules/rxjs/Observable.d.ts(1,15): error TS2307: Cannot find module 'rxjs-compat/Observable'.
node_modules/rxjs/Subject.d.ts(1,15): error TS2307: Cannot find module 'rxjs-compat/Subject'.

I saw other suggested solutions to this issue, but they are still confusing, need to update ngx-progressbar to another version? install other packages? I see some people wrote about core and http, should I also install them?
please let me know if you need any specific information, other than above, thank you very much.

**Comment by fchiumeo** [comment]
what error ?
please more information

**Comment by Bito165** [comment]
I'm experiencing this same issue.

**Comment by Bito165** [comment]
/node_modules/ngx-progressbar/modules/ngx-progressbar.es5.js
Module not found: Error: Can't resolve 'rxjs/add/observable/timer' 

@fchiumeo

**Comment by MurhafSousli** [comment]
You are using a very old version, the latest version works on Angular 6 too

**Comment by chr1soscl** [comment]
A very old version of what? Sorry that’s the confusing part, not sure what to upgrade, ngx-progressbar? The top update is 2.1.1.

**Comment by MurhafSousli** [comment]
@chr1soscl  Install `@ngx-progressbar/core` not `ngx-progressbar`

**Comment by MurhafSousli** [comment]
@chr1soscl There is no guide for upgrading, read [the docs](https://github.com/MurhafSousli/ngx-progressbar/wiki/Usage), it is short and simple

**Comment by briancaldass** [comment]
I have the same problem, none of the previous solutions works and @ ngx-progressbar / core does not work either and there is no documentation on how to use the core

**Comment by MurhafSousli** [comment]
@briancaldass https://github.com/MurhafSousli/ngx-progressbar/wiki
