### ISSUE TITLE
Error with angular 7

### ISSUE THREAD

**Issue by bogalex93** [MurhafSousli/ngx-progressbar#241]
### Bug Report 
Error in the browser console.
TypeError: rxjs_Observable__WEBPACK_IMPORTED_MODULE_3__.Observable.timer is not a function

### OS and Version?
 Windows 10.

**Comment by fchiumeo** [comment]
what version of rxjs used?

**Comment by bogalex93** [comment]
Hi, thank you for the quick response,
My version is ^6.3.3.

**Comment by MurhafSousli** [comment]
The problem is with your project, closing this as does not follow issue template and I don't think anyone can help you with the info you provided
