### ISSUE TITLE
Minor versioning broke my CI.

### ISSUE THREAD

**Issue by ScottMGerstl** [MurhafSousli/ngx-progressbar#244]
The change in commit https://github.com/MurhafSousli/ngx-progressbar/commit/1b76e0bfb7381bb82e6d1bd18dea1bf73c7dcf10 warrants a major version change. You broke the API for those using `forRoot`.

I fixed the issue locally to use `withConfig`. Please be aware of semantic versioning when publishing releases as most people have their package.json dependencies to allow minor version updates automatically using the `^` character

**Comment by MurhafSousli** [comment]
@ScottMGerstl I don't agree, I won't increment to version 6 for this tiny refactor even if it breaks the usage. The core code remains the same, take Angular or Material2 as examples, they also produce breaking changes from time to time without incrementing the major version. 
If they do the way you are saying, you would have been using angular v8973 now.

Anyone who wants to update this package should take a look at the [changelog](https://github.com/MurhafSousli/ngx-progressbar/blob/master/CHANGELOG.md).

I appreciate your feedback!

**Comment by ScottMGerstl** [comment]
@MurhafSousli It's your project and you can do what you like with it but here is the part of the spec that I am referring to. https://semver.org/#spec-item-8

**Comment by MurhafSousli** [comment]
@ScottMGerstl I am aware of this, it is true, some were complaining the same when Angular used to do a lot of breaking changes in the past, here material2 breaking changes in the last major version only:
https://github.com/angular/material2/blob/master/CHANGELOG.md#breaking-changes-3 https://github.com/angular/material2/blob/master/CHANGELOG.md#breaking-changes-2 https://github.com/angular/material2/blob/master/CHANGELOG.md#breaking-changes-1 https://github.com/angular/material2/blob/master/CHANGELOG.md#breaking-changes

**Comment by stevenvanryckeghem** [comment]
I follow @ScottMGerstl... It's indeed possible that in the actual code it's only a tiny refactor. But the API should be consistent between "minor" updates or should be backwards compatible. Now I ended up wondering why my build broke...

The links you listed are between RC and Beta releases though, so it's 'normal' there that between those versions, there are a lot of breaking changes. You can expect that RC's and Beta's aren't stable.

Also more information about NPM and semver and why it's important to follow those conventions as an NPM package author: https://docs.npmjs.com/about-semantic-versioning

Anyway, the damage is already been done. It's just a remark for the next release(s).

For the rest, good work on this library! It's simple and does the job!
