### ISSUE TITLE
Cant import module forRoot()

### ISSUE THREAD

**Issue by arctican** [MurhafSousli/ngx-progressbar#245]
I've just updated the package to the latest version, however I am no longer able to import the package:

`imports: [NgProgressModule.forRoot(),]` 
now results in 
`Property 'forRoot' does not exist on type 'typeof NgProgressModule'.`

Thanks

**Comment by MurhafSousli** [comment]
Please see the [changelog ](https://github.com/MurhafSousli/ngx-progressbar/blob/master/CHANGELOG.md) when you update the package
