### ISSUE TITLE
5.0.1 to latest: broken functionalities and questions

### ISSUE THREAD

**Issue by vajnorcan** [MurhafSousli/ngx-progressbar#247]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [x ] question
```

### OS and Version?

``` Windows 7, 10```
### Versions

```
node: v8.11.1
ng: 7.2.3
nxg-progressbar: 5.3.1
```

### Desired functionality

Upgrading from 5.0.1 to the latest broke the functionality, as listed:
- setting the progress bar service ref (which is new, service being accessed via ```.ref()``` values are not reflected in the ```ng-progress``` component (doesn't show any progress) even though the service gets the update

Questions:
- previously I could provide the id of the progress bar to the service and only the progress bar with that id would respond. why was this removed and what are my options as to how to control which progress bar will receive the service update?
- update the doco, apparently there is no ```.forRoot()``` anymore

Thank you for all your effort, and support.

**Comment by vajnorcan** [comment]
Alright, so after 2 hours I've finally figured it out. **Would be great if this was documented somewhere in wiki**

So in my scenario, I had a component that has the ```ng-progress``` component within and it **is within the *ngIf='isPending' **. This is rather important as you will find out later. Also, I have multiple similar progress bars, and as previously it all worked by telling the ngProgressService to what ```id``` I'm setting the value for, currently it's different.

Consider component html
```
<!-- Pending Overlay -->
  <div class="pending-overlay-white pending-overlay-column" *ngIf="isPending" [@toggle]="!isPending">
    <i class="icon-spinner icon-2x icon-spin-2x"></i>
    <div class="pending-overlay-description">Generating the viewshed area...</div>
    <div class="progress-container">
      <ng-progress id="viewshedbar" #viewshedbar [fixed]="false"></ng-progress>
    </div>
  </div
```

Then in some module, I'm setting the values for the service

```
  constructor(
    ...
    private ngProgressService: NgProgress,
    ...) {
    
    // Get the ngProgressRef to use the notifier service.
    this.ngProgressRef = ngProgressService.ref('viewshedbar');
  }
...
...
...
if (this.siteService.webworkerProgressBarId) {
                      if (msg === 'start') {
// THIS IS NEW AND IMPORTANT, and not documented unfortunately                        
                        this.ngProgressRef = this.ngProgressService.ref('viewshedbar');
                        this.ngProgressRef.set(0);
                      }
                      else if (msg === 'end') {
                        // this.ngProgressRef.complete(this.siteService.webworkerProgressBarId);
                        this.ngProgressRef.complete();
                        this.siteService.webworkerProgressBarId = null;
                      }
                      else if (typeof(msg) === 'number') {
                        // this.ngProgressRef.set(msg, this.siteService.webworkerProgressBarId);
                        this.ngProgressRef.set(msg);
                      }
                    }
```

### Answers to my questions
#### why it's not visible: 
well, the ```[fixed]=false``` attribute was missing in my implementation, as it's been introduced later, hence it was displaying elsewhere
#### why setting the value in the service wasn't reflected in the component
I had to add ```.ref(**id**)``` on the service. Previously this was not required
#### why it worked only once 
if user has performed the action that was triggering ```isPending```, new instance of the ```ng-progress``` was being generated, and so was the instance of the ```observable``` in the the service registry, hence I had to add ``` this.ngProgressRef = this.ngProgressService.ref('viewshedbar');``` inside my function each time it started to make sure that my triggering component and the progress displaying component have a pointer to exactly the same subject.

Hope that helps somebody

**Comment by MurhafSousli** [comment]
Thanks for your feedback, I fixed the docs
