### ISSUE TITLE
progressRef is not defined when using progress.isStarted property from template

### ISSUE THREAD

**Issue by swymmwys** [MurhafSousli/ngx-progressbar#248]
```
- [x] bug report
- [ ] feature request
- [ ] question
```

### Versions

"@ngx-progressbar/core": "^5.3.1"
"@ngx-progressbar/router": "^5.3.1"

### Repro steps

```html
<div [ngClass]="{red: progress?.isStarted}"></div>
<ng-progress #progress></ng-progress>
```
### Result
```
ERROR TypeError: Cannot read property 'isStarted' of undefined NgProgressComponent.get isStarted
```

**Comment by MurhafSousli** [comment]
This is weird, `isStarted` is a getter property in `NgProgressComponent`, it does not exist when the component is used from the template or using `@ViewChild()`

Here is [repro stackblitz ](https://stackblitz.com/edit/ngx-progressbar-fx6jrc?file=src/app/app.component.ts) to the issue 

---
But the following works well!

```html
<div [class.red]="progress.isStarted"></div>
<ng-progress #progress></ng-progress>
```
[Working stackblitz](https://stackblitz.com/edit/ngx-progressbar-f5xoy3?file=src%2Fapp%2Fapp.component.html)

**Comment by swymmwys** [comment]
@MurhafSousli maybe it's not issue of "ng-progress" it self, but some feature of how angular process different types of directives (I mean lifecycle order) like "ngClass" compared to [class.red] (native property).
