### ISSUE TITLE
Strange UI effect

### ISSUE THREAD

**Issue by MarcelWouters** [MurhafSousli/ngx-progressbar#249]
There ng-progress works perfect but I have some strange UI effect. See this picture.

![image](https://user-images.githubusercontent.com/13195094/52521013-064ac200-2c71-11e9-8091-c800f2b7a4aa.png)

In the right corner there is some strange effect.

I'm also using Bootstrap 4. Is there a conflict between CSS properties?

**Comment by MurhafSousli** [comment]
No, there is no CSS conflict, that part should be hidden.

If you change its default position from top, then you should use `overflow: hidden` on its parent container to hide that part or just disable the `meteor` style: `[meteor]="false"`
