### ISSUE TITLE
Allow user defining matched endpoint to catch for silent apis

### ISSUE THREAD

**Issue by ShakurOo** [MurhafSousli/ngx-progressbar#254]
## Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x] feature request
- [ ] question
```
## Desired functionality
It could be nice to define a new property for _NgProgressHttpModule_ called `matcher` which can accepts two differents type of values : 
 - `/api`: Whatever the protocole, subdomain, domain and possible folders are, this matcher will handle all segments included in `silentApis` option which are after `/api` segment
 - `/(http[s]?:\/\/|\w+(?=\.)|\.\w+)/g`: This option is more flexible/permissive. With this regex matcher, I handle urls with any subdomain.

## Why this feature ?
Depends on environments (dev, preprod, prod) and possible subdomains this feature prevents the user pasting all possible static url's which have to be catched by the module to be "silent".

In the case where a string is used : 

```
  NgProgressHttpModule.withConfig({
    silentApis: ['/places', '/user', 'reviews'],
    matcher: '/api'
  })
```

The possible handled url's are : 
- domain.com/api/places
- subdomain.domain.com/api/user
- domain.com/reviews/api/reviesw

In the case where a REGEX is used :

```
  NgProgressHttpModule.withConfig({
    silentApis: ['/places', '/user', 'reviews'],
    matcher: `https?:\/\/(\S*\.)?domain\.com`
  })
```

With this way, the handled url's are : 
- api.domain.com/places
- preprod.domain.com/user
- domain.com/reviews

The `matcher` option is optinnal. 
If it not used, you can just let the current behavior.

**Comment by MurhafSousli** [comment]
Looks like a nice feature, PRs are welcome!
