### ISSUE TITLE
Long Running Operation Indicator

### ISSUE THREAD

**Issue by craig-dae** [MurhafSousli/ngx-progressbar#255]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x] feature request
- [ ] question
```

### Desired functionality
I would like to see some kind of long-running-operation feature. We have a long spin-up time for our RDSs, which we don't intend to have in production, but comes up a lot in demos and testing. While that's another problem outside of ngx-progressbar, it would be nice to have some setting where, if an HTTP call lasted more than a few seconds (configurable), the progress bar would escalate to a spinner or something. It would convey the message "Yes, this is taking a long time, but nothing has failed yet. Please be patient".

**Comment by MurhafSousli** [comment]
Do you have a design proposal for this?

You can calculate if it takes long time using `(start)` output

```html
<ng-progress (start)="startARequestTimer()"></ng-progress>
```
```ts
startARequestTimer() {
   // ... timer
   if (elapsed > 5) {
       this.alert.show('Loading, Please be patient...')
   }
}
```

We can add something like the following

```html
<ng-progress [longTime]="5" (longTimeHappened)="onTakingLongTime()"></ng-progress>
```

**Comment by craig-dae** [comment]
I haven't come up with any clever ideas for this. I was hoping you could. This only happens in our dev/test/demo accounts because our RDSs are cold, so I can't justify putting any hours into designing a solution. That's why I tossed it to you, hoping it would be a popular feature request. 

But since I pitched this in April, and I didn't get any thumbs ups or responses for the idea, I won't be offended if you close this issue due to lack of interest.
