### ISSUE TITLE
Timer function imported from a different class

### ISSUE THREAD

**Issue by raghavsmartdata** [MurhafSousli/ngx-progressbar#256]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
- [ ] question
```

### OS and Version?

Issue can be traced on any major browser and using any OS distribution.

### Versions

Angular CLI v6.2.3

### Repro steps

When using rxjs v6+ . On using the ngx-progressbar. A issue can be seen when making an HTTP request, which states that timer is not a function of class Observable. 

### The log given by the failure

TypeError: rxjs_Observable__WEBPACK_IMPORTED_MODULE_3__.Observable.timer is not a function
    at SwitchMapSubscriber.project

### Desired functionality

Should work fine when loading data without producing any error in the console.

### Mention any other details that might be useful

The timer function should be imported from rxjs rather than Observable class.

**Comment by MurhafSousli** [comment]
Please add a repro https://stackblitz.com/edit/ngx-progressbar
