### ISSUE TITLE
Hide glow stick when progress bar is at bottom of parent element

### ISSUE THREAD

**Issue by ErikHumphrey** [MurhafSousli/ngx-progressbar#257]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [x] question
```

### Desired functionality

I have an ng-progress-bar in an ion-nav container as pictured below. I put it in a div so that I can still use the `overflow: hidden` declaration because it's the last element in the container (otherwise it would hide everything but the glow stick of the meteor progress bar). 

![image](https://user-images.githubusercontent.com/1473776/61800793-ab122380-adfb-11e9-8b40-f3577626cf52.png)

However, the glow stick from the meteor effect isn't being hidden by `overflow: hidden`! It seems a lot more difficult than if it was on the top of a div because the glow stick is angled upwards rather than downwards. I'm looking to hide the glow stick while still using the meteor effect, so that the progress bar only appears below the ion-nav. Any ideas?

**Edit:** In a way, I sort of just to have the progress bar be at the bottom of the container, or right after it (as if it was `::after`). Would *visually* be layered below the ion-nav despite the high z-index.

### Other info

Project isn't OSS and can't make a StackBlitz of the problem but can answer questions about it

**Comment by MurhafSousli** [comment]
Have you had a look at this example https://stackblitz.com/edit/ngx-progressbar-mutliple-instances?

**Comment by ErikHumphrey** [comment]
Aye, forgot to mention that. Seems straightforward if the overflow is on top, but I haven't managed to move the progress bar to the bottom of the panel in that example without the glow stick. Right now I'm just moving my progress bar with `top: 48px`.

**Comment by MurhafSousli** [comment]
Use a wrapper element that has `overflow: hidden` to wrap the progress bar

**Comment by ErikHumphrey** [comment]
Looks like I was just doing it wrong somehow. I'll share my fix if anyone else has the same issue.
