### ISSUE TITLE
Angular 8 has deprecated @angular/http

### ISSUE THREAD

**Issue by khellinx** [MurhafSousli/ngx-progressbar#258]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
- [ ] question
```

### OS and Version?
OS X Mojave

### Versions
```
Angular CLI: 8.1.2
Node: 10.16.0
OS: darwin x64
Angular: 8.1.2
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.801.2
@angular-devkit/build-angular      0.801.2
@angular-devkit/build-ng-packagr   0.801.2
@angular-devkit/build-optimizer    0.801.2
@angular-devkit/build-webpack      0.801.2
@angular-devkit/core               8.1.2
@angular-devkit/schematics         8.1.2
@angular/cdk                       8.1.1
@ngtools/json-schema               1.1.0
@ngtools/webpack                   8.1.2
@schematics/angular                8.1.2
@schematics/update                 0.801.2
ng-packagr                         5.3.0
rxjs                               6.5.2
typescript                         3.4.5
webpack                            4.35.2
```

### Repro steps
Install latest package in a new angular 8 project and try to build.
Since there is no @angular/http v8.x package, the build fails because the public_api exports NgProgressBrowserXhr, which in its turn imports BrowserXhr from @angular/http.

### The log given by the failure
```ERROR in node_modules/ngx-progressbar/src/services/browser-xhr.provider.d.ts(1,28): error TS2307: Cannot find module '@angular/http'.```

### Desired functionality
Add possibility to not have to include the @angular/http package.

### Mention any other details that might be useful
Might be somewhat related to issue 61

**Comment by MurhafSousli** [comment]
You have installed the wrong package, use `@ngx-progressbar/core` and `@ngx-progressbar/http` instead
