### ISSUE TITLE
Display time elapsed for HTTP requests while progressbar active

### ISSUE THREAD

**Issue by raviada** [MurhafSousli/ngx-progressbar#261]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [X ] question
```
Is there a way to display elapsed time while progress bar is in progress or at the end of the request finished?

```|------0.2sec                  |```
or 
```|-----------------------| 2.5 secs```

Thanks
Ravi Ada

**Comment by MurhafSousli** [comment]
We cannot determine when the request will finish, the progress is fake
