### ISSUE TITLE
11 rest calls in forkJoin

### ISSUE THREAD

**Issue by raviada** [MurhafSousli/ngx-progressbar#262]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [X ] question
```
I have 11 rest calls made in parallel. I want to show progressbar for each one as it finished in a list format as below.
```
restcall1
|--------------------|
restcall2
|--------------------|
restcall3
|--------------------|
restcall4
|--------------------|
....
```

what is the best way to accomplish this? I used your example of multiple progress bars with ids, also grabbing reference to each progressbar, calling `start()` and `completed()` after subscribing to each call.

I see only one progressbar on the top instead of showing multiple at each list item. I am using `core` as well as `http` libraries.

Any help is appreciated.

**Comment by DoanVanThuong** [comment]
i think you should split it to multiple request by using function
