### ISSUE TITLE
Not working with angular 8

### ISSUE THREAD

**Issue by ShivPandey** [MurhafSousli/ngx-progressbar#263]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [ ] question
```

**Comment by MurhafSousli** [comment]
What is the given error ?

**Comment by ShivPandey** [comment]
start() is not a known method in NgProgress

**Comment by shubhambattoo** [comment]
Basically the library is using old @angular/http library which was deprecated, and also the rxjs libraries are also old. Got no module find errors.

**Comment by MurhafSousli** [comment]
This library doesn't use @angular/http since ages! I have said this million times in the issues! please pay attention to the docs, the package you should be using is `@ngx-progressbar/core`
