### ISSUE TITLE
Angular Universal NgProgressRouterModule causes ~500 ms delay

### ISSUE THREAD

**Issue by lukaszzieba** [MurhafSousli/ngx-progressbar#277]
Importing module NgProgressRouterModule causes ~500 ms delay while angular runs on server.

#### Reproduction
Steps to reproduce:
1.  For create new project: **ng new ssr-test**
2. For add server side rendering: **ng add @nguniversal/express-engine**
 (now you can run: **npm run build:ssr** and **npm run serve:ss**r to check initial render time, it is  ~20 ms.)
3. Install ngx-progressbar: **npm i ngx-progressbar --save** 
4. Import modules to app.module:  
    - RouterModule.forRoot([])
    - NgProgressModule
    - NgProgressRouterModule
5. re run **npm run build:ssr** and **npm run serve:ssr** (now TTFB is ~500ms.)

#### Environment
- "@angualr": ~9.0.7
- "@nguniversal/express-engine": "^9.0.2",
- "express": "^4.15.2",
- "ngx-progressbar": "^6.0.2",
- Operating System: macOS

**Comment by infinitai** [comment]
any action on this? I had to remove the progressbar just for this reason. It was screwing the pagespeed score from 80 to 60 in mobile.

**Comment by MurhafSousli** [comment]
I have no idea why it causes a delay on your end, any help on investigating the issue is appreciated! it is probably something in [progress-router.service.ts](https://github.com/MurhafSousli/ngx-progressbar/blob/master/projects/ngx-progressbar/router/src/ng-progress-router.service.ts)

**Comment by MurhafSousli** [comment]
Closing for inactive for so long...
