### ISSUE TITLE
spinner without bar

### ISSUE THREAD

**Issue by sarahBuisson** [MurhafSousli/ngx-progressbar#282]
Hello
I want to use your spinner, but I want to do it with only the spinner, not the bar

How Do I do that?

My code:

`          <ng-progress #progressSpinner  [min]="20" [max]="1" [speed]="200" [trickleSpeed]="300"
                       [spinner]="true"
                       [fixed]="false"
                       started = onStarted()
                  ></ng-progress>`

**Comment by MurhafSousli** [comment]
You should, you can use the progress reference `NgProgressRef` and subscribe to the state, and show a spinner when it is activated

**Comment by sarahBuisson** [comment]
I don't understand, can you give me a code sample?

**Comment by MurhafSousli** [comment]
Check out the custom example here https://github.com/MurhafSousli/ngx-progressbar/blob/master/src/app/custom/custom/custom.component.ts

```html
<ng-container *ngIf="progressRef.state | async as state">
    <mat-progress-bar *ngIf="state.active"></mat-progress-bar>
</ng-container>
```
```ts
export class CustomComponent implements OnInit, OnDestroy {

  progressRef: NgProgressRef;

  constructor(public ngProgress: NgProgress) {
  }

  ngOnInit() {
    this.progressRef = this.ngProgress.ref('material');
  }

  ngOnDestroy() {
    this.progressRef.destroy();
  }
}
```
