### ISSUE TITLE
NgProgressHttpModule - URLs in silentApis are Case Sensitive (must be small letters to work)

### ISSUE THREAD

**Issue by Hussein-Dahir** [MurhafSousli/ngx-progressbar#283]
#### Reproduction

Steps to reproduce:
Register NgProgressHttpModule with a URL that contains capital letters in **silentApis** array, just like this:
```
NgProgressModule,
NgProgressHttpModule.withConfig({
  silentApis: [
     "http://localhost/Item/GetItems"
  ]
})
```

#### Expected Behavior

What behavior were you expecting to see?
To silent this API URL, no matter the URL contains capital letters or small letters

#### Actual Behavior

What behavior did you actually see?
API won't get silent unless URL is in small letters only

#### Environment

- Angular: 8.2.5
- ngx-progressbar: http
- Browser(s): Chrome 83.0.4103.116
- Operating System (e.g. Windows, macOS, Ubuntu): Windows 10

**Comment by MurhafSousli** [comment]
Isn't the url supposed to be small?

**Comment by Hussein-Dahir** [comment]
> Isn't the url supposed to be small?

It is better to not make that a constraint, URL may contain capitalized letters (Controller name, API name),
just prefer not to convert that manually.

You can ignore that if you don't think it is an important thing, but in fact, I spent hours figuring out why silentApis is not working in my case, until I saw its code.

**Comment by MurhafSousli** [comment]
This is the first issue related to silentApis url case sensitivity, I would suggest that you convert it manually for now. I can keep this open for a while to see if others are having the same issue
