### ISSUE TITLE
change order of NgProgressInterceptor & CustomInterceptor

### ISSUE THREAD

**Issue by Hussein-Dahir** [MurhafSousli/ngx-progressbar#285]
#### What are you trying to do?
Change the order of NgProgressInterceptor  and MyCustomInterceptor

#### What troubleshooting steps have you tried?

In AppModule:

  imports: [
    NgProgressModule,
    NgProgressHttpModule,
  ],
  providers: [
    APIS,
    { provide: HTTP_INTERCEPTORS, useClass: MyCustomInterceptor, multi: true },
  ],

What are you trying to achieve?

How to change the order, so that MyCustomInterceptor we be entered before NgProgressInterceptor,
I need that to add **ignoreProgressBar** header in the interceptor with some condition to add it for some APIs only, since I cannot add it directly in method call, as mention in the [docs](https://github.com/MurhafSousli/ngx-progressbar/wiki/HttpClient-requests#1-ignore-a-specific-http-requests).

  
#### Environment

- Angular: 8.2.14
- ngx-progressbar: 6.0.1
- Browser(s): Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): Windows

**Comment by MurhafSousli** [comment]
It is unclear to me, what does changing the order do? can you provide a stackblitz that shows it

**Comment by Hussein-Dahir** [comment]
> It is unclear to me, what does changing the order do? can you provide a stackblitz that shows it

Simply, I want to put **ignoreProgressBar** header inside MyCustomInterceptor, and make MyCustomInterceptor getting hit before NgProgressInterceptor, so that **ignoreProgressBar** header will work.

If NgProgressInterceptor was hit first, then adding **ignoreProgressBar** header to MyCustomInterceptor  won't do anything, since request already passed NgProgressInterceptor.

**Comment by MurhafSousli** [comment]
Sorry for the delay, I didn't notice your reply!

Maybe you can solve it by changing your custom interceptor order, but from the source code of this plugin I don't think I can do anything about the order.

The usage of the `ignoreProgressbar` was meant to be used from an http call, not from another interceptor...

If you have an idea for an improvement I would appreciate it!
