### ISSUE TITLE
Progressbar compatible with promises instead of obervables

### ISSUE THREAD

**Issue by kingeric027** [MurhafSousli/ngx-progressbar#287]
#### Feature Description

Can ngx-progressbar be updated to work with promises as well as observables? 

#### Use Case

We are using an sdk handles http requests with promises instead of observables in our angular application. Currently the progressbars do not work on these http requests.

**Comment by MurhafSousli** [comment]
The http module is designed for the `HttpClientModule`, if you have handling the request in a different way, you should start and complete it manually, or write your custom interceptor for automatically run the progress bar with your SDK requests
