### ISSUE TITLE
Add the Licence in NPM JS

### ISSUE THREAD

**Issue by samysammour** [MurhafSousli/ngx-progressbar#290]
#### Documentation Feedback

Hi,

Thanks for developing the library, it is really useful!
Can you please add the Licence to the [npmjs](https://www.npmjs.com/package/ngx-progressbar) because the licence there is set to none which means, we cannot use it in our products.

Thank you and have a nice week!

**Comment by MurhafSousli** [comment]
This was fixed in v6.0.4
