### ISSUE TITLE
Unexpected finish while switchMap (ngrx operator) cancel first request

### ISSUE THREAD

**Issue by cichy380** [MurhafSousli/ngx-progressbar#292]
#### Reproduction

Use StackBlitz to reproduce your issue: https://stackblitz.com/edit/ngx-progressbar-uc5xxx

Steps to reproduce:
1. Double click quickly button
2. After second button click NgProgressRef.completed emits value immediately
 
 
#### Expected Behavior
I expected that progress bar will be visible till second request finished

#### Actual Behavior
Progress bar "finishes work" when first request is canceled

#### Environment
- Angular: 10
- ngx-progressbar: 6.0.3
- Browser(s): Chrome 86.0.4240.198
- Operating System: Windows

**Comment by MurhafSousli** [comment]
@cichy380 sorry for delay!

If you have multiple requests running at the same time, the progress will only complete when all requests are finished / cancelled

But in your case, you are cancelling the only request before running the next one so it the progress completes.

In the http package, when you cancel a request, it will execute the `finalize` operator which completes the progress bar.

https://github.com/MurhafSousli/ngx-progressbar/blob/f482b6971f23b922aa45ab27b794410b859ce488/projects/ngx-progressbar/http/src/ng-progress.interceptor.ts#L41-L48

Do you know a better solution?

**Comment by MurhafSousli** [comment]
Closing for now... feel free to continue the discussion or to reopen!
