### ISSUE TITLE
Upgrade and Rename package to ngx-progressbar

### ISSUE THREAD

**Issue by mkennedy3000** [MurhafSousli/ngx-progressbar#31]
@MurhafSousli, first off, thank you for this package. It's awesome.

I was wondering if you would consider upgrading to the latest Angular version and renaming this package to `ngx-progressbar` to comply with the "Just Angular" idea (http://angularjs.blogspot.com/2016/12/ok-let-me-explain-its-going-to-be.html)

If you would like some help doing this, I'd be more than happy to contribute.

**Comment by MurhafSousli** [comment]
Hi @mkennedy3000 yes I'm planning to adapt the "Just Angular" very soon
