### ISSUE TITLE
NullInjectorError: R3InjectorError(AppModule)[NgProgressRef -> NgProgressRef -> NgProgressRef

### ISSUE THREAD

**Issue by AmarDK** [MurhafSousli/ngx-progressbar#320]
#### Steps Taken

Previously project was Angular 4, So I migrated to Angular 13(Latest Version).

**In Angular 4, below are the steps taken care and respective version**
**ngx-progressbar**: 2.1.1
import { NgProgress } from 'ngx-progresssbar';
Injecting ngProgress: NgProgress

**To start progress and to complete below process is taken care.**
ngProgress.start();
ngProgress.done(); 

In Angular 13, below are the steps taken care and respective version
**ngx-progressbar**: 6.1.1
import { NgProgressRef} from 'ngx-progresssbar';
Injecting ngProgressRef: NgProgressRef

**To start progress and to complete below process is taken care.**
ngProgressRef.start();
ngProgressRef.complete(); 

#### Actual Behavior

What behavior did you actually see?

I just updated from **NgProgress** to **NgProgressRef**,

When I do serve, I get **NullInjectorError: No provider for NgProgressRef!**

Please refer for the screenshot 
![ngProgressRef](https://user-images.githubusercontent.com/37371290/143389944-cca49c9c-36db-4da9-9646-bcefa90164c6.png)

#### Environment

- Angular: 13
- ngx-progressbar: 6.1.1
- Browser(s): Mozilla Firefox
- Operating System (e.g. Windows, macOS, Ubuntu):  Ubuntu

**Comment by MurhafSousli** [comment]
Since you were upgrading from v4 to v13, the problem is probably caused by that
