### ISSUE TITLE
a11y - Ability to add a label to the progress bar.

### ISSUE THREAD

**Issue by crotru** [MurhafSousli/ngx-progressbar#321]
#### Feature Description

Ability to add a label to the progress bar.
An element with a `progressbar` aria role must have a label (as text alternative for non-text content)
see https://www.w3.org/WAI/WCAG21/Understanding/non-text-content.html
and https://dequeuniversity.com/rules/axe/4.1/aria-progressbar-name

#### Use Case

It would be great to be able to add this to the config
something like :
```ts
NgProgressModule.withConfig({
  label: 'main content loading',
})
```

**Comment by MurhafSousli** [comment]
The host component already has `role="progressbar"` and I think there is no need to add `aria-label`, `aria-labelledby` and other attributes to the host component from the library since the user can easily add them directly.
