### ISSUE TITLE
a11y - ProgressBar direction shouldn't be bound on html dir attribute.  

### ISSUE THREAD

**Issue by crotru** [MurhafSousli/ngx-progressbar#322]
#### Feature Description

_Not sure if this fits in bug or feature..._

ProgressBar direction shouldn't be bound to html `dir` attribute. 
As you know we give `dir` a value of `ltr+`, `ltr-`, `rtl+` or `rtl-`, but `dir` global attribute only accepts `ltr`,  `rtl` or `auto`
(see https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/dir)

It would maybe better to bind it to a custom attr like `direction`, `bar-dir`, or something like that.

I don't feel like the `dir` attribute conveys a really meaningful information so we could maybe drop it,
(but if you feel it should stay it should hold `ltr` or `rtl`)

**Comment by MurhafSousli** [comment]
You're right and I agree with this in general but since the progress bar is a custom component and doesn't accept child elements (it cannot be used as wrapper) then there will be no potential harm what so ever.
