### ISSUE TITLE
Error occur when using angular 2 routing

### ISSUE THREAD

**Issue by fawadmukhtar** [MurhafSousli/ngx-progressbar#34]
EXCEPTION: Uncaught (in promise): Error: Error in ./e class e - inline template:9:6 caused by: object unsubscribed
Error: Error in ./e class e - inline template:9:6 caused by: object unsubscribed

I am new in angular2, 
when I use ng progress bar in my angular 2 project then there is no error occur but when I use routing then throw an error which is mentioned above, when I commit " <ng-progress></ng-progress>" then project works normally,  please fix it,

**Comment by FunClub** [comment]
i have the same error
