### ISSUE TITLE
Package "ngx-progressbar" was found but does not support schematics.

### ISSUE THREAD

**Issue by ohbus** [MurhafSousli/ngx-progressbar#346]
#### Reproduction

Use StackBlitz to reproduce your issue: https://stackblitz.com/edit/ngx-progressbar

Steps to reproduce:
1. ng add ngx-progressbar
 
 
#### Expected Behavior

What behavior were you expecting to see?
Successful install

#### Actual Behavior

What behavior did you actually see?
Unsuccessful install

#### Environment

- Angular: 15.0.0
- ngx-progressbar: 9.0.0
- Browser(s): Chrome 107.0.5304.110
- Operating System (e.g. Windows, macOS, Ubuntu): macOS

```bash
Angular CLI: 15.0.0
Node: 16.15.0
Package Manager: npm 8.5.5
OS: darwin arm64

Angular: 15.0.0
... animations, cdk, cli, common, compiler, compiler-cli, core
... forms, material, platform-browser, platform-browser-dynamic
... router, service-worker

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1500.0
@angular-devkit/build-angular   15.0.0
@angular-devkit/core            15.0.0
@angular-devkit/schematics      15.0.0
@schematics/angular             15.0.0
rxjs                            7.5.7
typescript                      4.8.4
```

**Comment by kariudo** [comment]
That is not an error.

`ng add ngx-progressbar` will still tell your configured package manager (npm/yarn) to install the package, it just does not include schematics (ng cli will always warn of that if you used it to install a package without them).

You could just use `npm` or `yarn` to add it.
