### ISSUE TITLE
Any way to load when bootstrapping?

### ISSUE THREAD

**Issue by KlarityStudio** [MurhafSousli/ngx-progressbar#35]
Hi, I have implemented this loader seamlessly into our project. Thanks for the great module!

Is it possible and how would I go about using it to show the loading bar when the app first bootstraps/loads?

**Comment by MurhafSousli** [comment]
Hello @KlarityStudio, you are welcome
Unfortunately this is not possible, you can not use any angular component until the app is fully loaded

**Comment by KlarityStudio** [comment]
Thank you for getting back. Yes I know this but was hoping there was a way
to still use the html and css from the module so the loader style is
consistent.
