### ISSUE TITLE
Initiate on route change?

### ISSUE THREAD

**Issue by KlarityStudio** [MurhafSousli/ngx-progressbar#36]
Is there a way to initiate the progress when changing routes in Angular?

**Comment by MurhafSousli** [comment]
Yes, you can subscribe to router changes in your root component to start the progress using the service
Make sure the progress bar is somewhere outside the 'router-outlet' so it doesn't get destroyed when you navigate between the routes.

**Comment by MurhafSousli** [comment]
I closed the issue by my mistake, I'm on mobile. I will write the code when I get back home

**Comment by MurhafSousli** [comment]
**Example code**

In root component
```ts
constructor(private router: Router, private progress: NgProgressService) { 

    router.events
       .filter(event => event instanceof NavigationEnd)
       .subscribe(() => progress.start());
}
```

**Comment by KlarityStudio** [comment]
This worked perfectly thanks!
