### ISSUE TITLE
Not Working for Angular 17

### ISSUE THREAD

**Issue by pcsaini** [MurhafSousli/ngx-progressbar#365]
#### Reproduction

Use StackBlitz to reproduce your issue: https://stackblitz.com/edit/ngx-progressbar

Steps to reproduce:
1. npm i ngx-progressbar
 
 
#### Expected Behavior

What behaviour were you expecting to see?
Install smoothly

#### Actual Behavior

What behaviour did you actually see?
Not Working

#### Environment

- Angular: 17
- ngx-progressbar: 11.1.0
- Browser(s): Chrome
- Operating System (e.g. Windows, macOS, Ubuntu):

**Comment by jahller** [comment]
what issue do you see? the stackblitz you provided is working fine

**Comment by msjahun** [comment]
> #### Reproduction
> Use StackBlitz to reproduce your issue: https://stackblitz.com/edit/ngx-progressbar
> 
> Steps to reproduce:
> 
> 1. npm i ngx-progressbar
> 
> #### Expected Behavior
> What behaviour were you expecting to see? Install smoothly
> 
> #### Actual Behavior
> What behaviour did you actually see? Not Working
> 
> #### Environment
> * Angular: 17
> * ngx-progressbar: 11.1.0
> * Browser(s): Chrome
> * Operating System (e.g. Windows, macOS, Ubuntu):

I just tried it in angular 17 and it still works
