### ISSUE TITLE
z-index for pregressbar

### ISSUE THREAD

**Issue by nitinkumarmishra** [MurhafSousli/ngx-progressbar#39]
![image](https://cloud.githubusercontent.com/assets/14124584/26283971/ec38743c-3e4e-11e7-8273-4929ae1ed733.png)
Can you guys just increase the z-index of host element to more then 1030 so that it should visible to the screen currently  this bar is rendering below the topnav which has z-index 1030 (not visible).

**Comment by MurhafSousli** [comment]
@nitinkumarmishra I think we can increase it in a future update

**Comment by MurhafSousli** [comment]
Okay, the issue was actually in the old workflow the sass task was always compiling the z-index to `1` in the build no matter what the value is in the source (so weird right! ).
I updated the workflow and now it is working.

Update to **v2.0.2** 👍

**Comment by MurhafSousli** [comment]
fixed in **v2.0.3**
