### ISSUE TITLE
Unsubscribe error with Angular 4 and ng2-progress component

### ISSUE THREAD

**Issue by office-work-account** [MurhafSousli/ngx-progressbar#41]
When using ng2-progress with routing and observable in Angular 4, ng2-progress cause errors with unsubscribe.

**Comment by MurhafSousli** [comment]
Hi @office-work-account.

`ng2-progressbar` is deprecated. it is `ngx-progressbar` now

This issue is a duplicate of #27 and #28 

_Short answer_

**DO NOT Add the `<ng-progress>` in a child component! ALWAYS add it in a root component where the progress bar doesn't get destroyed**
