### ISSUE TITLE
Do not use v2.0.2 in AOT

### ISSUE THREAD

**Issue by MurhafSousli** [MurhafSousli/ngx-progressbar#45]
**v2.0.2** is not working in AOT, Use **v2.0.0** until it is fixed.

**Comment by jmorganmartin** [comment]
I wish I had seen this earlier yesterday. Bug was driving me nuts.

**Comment by MurhafSousli** [comment]
@jmorganmartin  2.0.1 was supposed to increase z-index, but the style task was weirdly compiling the `z-index` to 1 no matter what value I use, so I had to change the whole workflow. I tried this [workflow library](https://github.com/jvandemo/generator-angular2-library) and it caused the bug in AOT

**Comment by MurhafSousli** [comment]
Fixed in **v2.0.3**
