### ISSUE TITLE
Cannot find name 'BrowserXhr'

### ISSUE THREAD

**Issue by rob-weiss** [MurhafSousli/ngx-progressbar#47]
Trying to add the provider like described in the README

```
import { NgProgressBrowserXhr } from 'ngx-progressbar';

@NgModule({
 providers: [
   // ...
   { provide: BrowserXhr, useClass: NgProgressBrowserXhr } ,
 ],
 imports: [
   // ...
   NgProgressModule
 ]
})
```

my editor says `Cannot find name 'BrowserXhr'`.

**Comment by MurhafSousli** [comment]
Hi @rob-weiss I forgot to add this line in the README, `import {BrowserXhr} from '@angular/http';`
