### ISSUE TITLE
XMLHttpRequest is not defined at NgProgressBrowserXhr.BrowserXhr.build

### ISSUE THREAD

**Issue by rob-weiss** [MurhafSousli/ngx-progressbar#48]
I followed the updated instructions for the automagic loading bar and get the following error:

```
XMLHttpRequest is not defined at NgProgressBrowserXhr.BrowserXhr.build
```

**Comment by MurhafSousli** [comment]
@rob-weiss I am not sure, Did you import `HttpModule` ?

**Comment by rob-weiss** [comment]
Yes, I did.

**Comment by MurhafSousli** [comment]
@rob-weiss Add your full usage of the module

**Comment by rob-weiss** [comment]
Please see here:

My main module
[`app.module.ts`](https://github.com/rob-weiss/Data-Visualisation/blob/master/Implementation/App/Client/app/app.module.ts)

and my main component
[`app.component.html`](https://github.com/rob-weiss/Data-Visualisation/blob/master/Implementation/App/Client/app/app.component.html)

I am new to Angular and TypeScript development. Do I have to load the NgProgressBar modules in both [`app.module.ts`](https://github.com/rob-weiss/Data-Visualisation/blob/master/Implementation/App/Client/app/app.module.ts) and in [`browser-app.module.ts`](https://github.com/rob-weiss/Data-Visualisation/blob/master/Implementation/App/Client/app/browser-app.module.ts)?

**Comment by MurhafSousli** [comment]
There is a lot of mess in the code, why don't you make sub modules to ease the readability 
```ts
import { NgProgressModule } from 'ngx-progressbar';
import {NgProgressService} from 'ngx-progressbar';  // <- what for?
import { BrowserXhr } from '@angular/http';
import { NgProgressBrowserXhr } from 'ngx-progressbar';
```
Why not
```ts
import { BrowserXhr } from '@angular/http';
import { NgProgressBrowserXhr, NgProgressBrowserXhr } from 'ngx-progressbar';
```
It is still not clear why you are getting the error, I personally use `NgProgressModule` with a custom http and it works without any problems.

The conflict can be in `TransferHttpModule` you only need one Http module either `TransferHttpModule` or `HttpModule`. not both

Try to remove `HttpModule` and try again and check your custom http again

A basic custom http module should look something like this
```ts
/** Custom Http Factory */
export function customHttpFactory(backend: XHRBackend, defaultOptions: RequestOptions) {
  return new CustomHttp(backend, defaultOptions);
}

@NgModule({
  declarations: [
    //..
  ],
  imports: [
    HttpModule
  ],
  providers: [
       {
          provide: CustomHttp,
          useFactory: customHttpFactory,
          deps: [XHRBackend, RequestOptions]
        }
  ]
  exports: [
   //..
  ]
})
export class CustomHttpModule { }
```
_I highly recommend you to get a smarter text editor_

**Comment by rob-weiss** [comment]
I am an electrical engineer and new to web development. However, your 'Why not.. ' suggestion makes sense to me.

My code is based on [aspnetcore-angular2-universal](https://github.com/MarkPieszak/aspnetcore-angular2-universal#getting-started) template. Apart from adding a few components I hardly touched the code so far. @MarkPieszak, is there a specific reason why you're using both `TransferHttpModule` and `HttpModule`? I tried to delete the import but haven't been able to make it run since there are obviously some parts depending on both modules.

I'm using Visual Studio Code and ASP.NET Core as back-end. Any suggestions for an alternative text editor?

**Comment by MurhafSousli** [comment]
I am not familiar with that starter template, but I suggest you use [Angular-CLI](https://github.com/angular/angular-cli) for your projects.

VSCode is fine, you can make it smarter by installing some extension, check this [7 must have VSCode extension for Angular](https://medium.com/frontend-coach/7-must-have-visual-studio-code-extensions-for-angular-af9c476147fd)

**Comment by MarkPieszak** [comment]
@rob-weiss TransferHttp is used for when you want server-rendered Http calls to be cached into an object that's passed into the Html as a String, then parsed into a JS Object again when the client bootstraps, so that it can be re-used (instead of calling an API for the 2nd time, causing the screen to re-render as well).

**Comment by rob-weiss** [comment]
Thanks @MurhafSousli, I had already installed a few and installed most of the remaining ones you suggested. I think Angular-CLI is fine for new projects. However, to give me some momentum and to get going quickly @MarkPieszak's template is really helpful. It has the required features but not too much of what I don't need. For my current assignment I cannot start from scratch as time is limited. The template gave me a working Angular app featuring most of what I am trying to build, including ASP.NET back-end, in a minute.

@MarkPieszak, I assumed there is a reason why you used both. Thank you for clarifying this again!

**Comment by MurhafSousli** [comment]
closing this as not an issue, feel free to continue the discussion
