### ISSUE TITLE
Automagic loading but hiding the bar for certain petitions

### ISSUE THREAD

**Issue by alfupe** [MurhafSousli/ngx-progressbar#50]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search for a similar issue before submitting
[x] feature request
[x] question
```

Hi there, 
I'm "Automagicly loading" the progress bar and it's very cool and working very nice, although among all my petititions I have one of them that is very recurrent (every 8 seconds) and I would like to hide the progress-bar only for it. Is it possible?

Thanks a lot

**Comment by MurhafSousli** [comment]
Hi @alfupe, no currently it is not possible, automagic is for all http requests, if you want customize it for specific requests you will need to start and complete the progress bar manually

**Comment by alfupe** [comment]
It's OK, thank you @MurhafSousli. I will try to do the trick with the router and css.

**Comment by alfupe** [comment]
I think this feature is useful not only to me but others. Would you be open to contributions? Any advice before deep into the code?

Thanks

**Comment by MurhafSousli** [comment]
@alfupe yes sure, PRs are welcome. nothing really!

**Comment by adrienlamotte** [comment]
Hello @alfupe,
You could simply use an HttpInterceptor for that, something like : 
```
import { Observable } from 'rxjs/Observable';
import {HttpEvent, HttpInterceptor, HttpHandler, HttpRequest} from '@angular/common/http';
import { NgProgressService } from "ngx-progressbar";

@Injectable()
export class LoadingbarInterceptor implements HttpInterceptor {

  constructor(public progressService: NgProgressService) {}
 
  intercept(req: HttpRequest<any>, next: HttpHandler): Observable<HttpEvent<any>> {
    if(yourCondition) this.progressService.start();
    return next.handle(req).finally(()=>{
      this.progressService.done();
    });
  }
}
```
I did not tested it, but I use something similar in my app and it works great :)
Really cool plugin btw @MurhafSousli, thanks !

**Comment by alfupe** [comment]
wow @adrienlamotte I didn't know that this were possible. Thanks a lot! I'll test it in a few days and will return back to tell you ;-)

**Comment by adrienlamotte** [comment]
@alfupe I did not specified it, but it's a pretty new feature and you'll have to use Angular 4.3.

BTW, @MurhafSousli : I think your "automatic mode" doesn't work with the new HttpClient (at least for me) - that's why I used my HttpInterceptor in the first place.

**Comment by alfupe** [comment]
ahh good point @adrienlamotte! Luckily yesterday I updated to 4.3.4. Thanks again!

**Comment by MurhafSousli** [comment]
@adrienlamotte Good catch. It would be great if we can add a plug for `HttpClient` users.

**Comment by MurhafSousli** [comment]
Guys update to `2.0.4` for the new NgProgressInterceptor. @adrienlamotte thanks for the contribution
