### ISSUE TITLE
Is current NgProgressBrowserXhr xhr event override safe ?

### ISSUE THREAD

**Issue by gempain** [MurhafSousli/ngx-progressbar#51]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search for a similar issue before submitting
[ ] feature request
[ x] question
```

**Minimal usage of the plugin**
I was wondering if it is safe to assign events to the xrh request in [`NgProgressBrowserXhr`](https://github.com/MurhafSousli/ngx-progressbar/blob/master/src/services/browser-xhr.provider.ts#L14). Could this accidentally override other events bound by Angular ?

**Comment by MurhafSousli** [comment]
It is safe, it only hooks the xhr's events with the progress bar.

**Comment by gempain** [comment]
Thanks for the quick response ! That is an amazing lib you have written here :)

**Comment by MurhafSousli** [comment]
@gempain welcome
