### ISSUE TITLE
../node_modules/ngx-progressbar/index"' has no exported member 'NgProgressCustomBrowserXhr'.

### ISSUE THREAD

**Issue by mac10046** [MurhafSousli/ngx-progressbar#52]
Hi,

I am getting an error on ng build command which stated as follows:

```
WARNING in ./src/app/app.module.ts
52:49-75 "export 'NgProgressCustomBrowserXhr' was not found in 'ngx-progressbar'
....../node_modules/ngx-progressbar/index"' has no exported member 'NgProgressCustomBrowserXhr'.

```

It use to work well, before I deleted the node_modules folder and reinstall all dependencies today (used npm install) - and I use ng-cli

version used: "ngx-progressbar": "^2.0.0"
I also upgraded to version 2.0.3 but same error persist

**Comment by fchiumeo** [comment]
NgProgressCustomBrowserXhr has rename to NgProgressBrowserXhr 
@MurhafSousli add this note in changelog
