### ISSUE TITLE
Multiple progress on one template

### ISSUE THREAD

**Issue by kama1** [MurhafSousli/ngx-progressbar#53]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search for a similar issue before submitting
[ ] feature request
[x] question
```

Is it possible to have multiple progress on one template? and if it is possible could you please point me to right direction to use it?

**Comment by MurhafSousli** [comment]
Hi @kama1, currently it is not possible. we are using a singleton service to let the users start/stop the progress without the need to pass the `ProgressComponent` reference with each function such as `progress.start(progressbar1)`

P.S: I won't mind accepting a PR for multiple instances feature
