### ISSUE TITLE
object unsubscribed error

### ISSUE THREAD

**Issue by FunClub** [MurhafSousli/ngx-progressbar#54]
could you help me?

**Comment by MurhafSousli** [comment]
Hi @FunClub, you need to provide more information about your setup and include you usage code (make sure you put in a readable format) and the Angular version you are using

**Comment by FunClub** [comment]
Sorry.My English is poor.
i use:
1.angular version:4.0
2.progressbar version 2.0.3
my code :

in module.ts
`@NgModule({
  imports: [
    NgProgressModule,
    other.....
  ],`

in component.ts
` 
constructor(private progressService: NgProgressService,) {
  }

 ngOnDestroy(): void {
        this.progressService.trickling.unsubscribe();
       this.progressService.state.unsubscribe();
  }

doLogin() {
           this.progressService.start();

      this.loginService.login(this.loginForm.value).subscribe(res => {
        this.progressService.done();
            this.router.navigateByUrl("home");
          //.........
      });
    }
`
in html
<ng-progress [positionUsing]="'marginLeft'" [minimum]="0.15" [maximum]="1"
             [speed]="'200'" [showSpinner]="'false'" [direction]="'rightToRightIncreased'"
             [color]="'red'" [trickleSpeed]="250" [thick]="false" [ease]="'linear'"
></ng-progress>

that is all.when call  this.router.navigateByUrl("home")  to the home-page,you will see a 'object unsubscribed' error  in the console. 
if i dont use ngx-progressbar the error will disappear. I have to call unsubscrib method explicit?  could you help me? thanks.

**Comment by MurhafSousli** [comment]
>  ngOnDestroy(): void {
this.progressService.trickling.unsubscribe();
this.progressService.state.unsubscribe();
}

Ofcourse! Why do you unsubscribe in `ngOnDestroy`?
Unsubscribing is handled out of the box. just follow the instructions in README
