### ISSUE TITLE
add events

### ISSUE THREAD

**Issue by reza3vi** [MurhafSousli/ngx-progressbar#55]
hi.

may to add event callback to progressbar.
on start
on end
on progress (percentage)

:)

**Comment by MurhafSousli** [comment]
Hi @reza3vi I am not sure if this is useful, let's keep this open for votes

**Comment by MurhafSousli** [comment]
@reza3vi You can subscribe to the progress state using the **NgProgressService**
```ts
 constructor(public progress: NgProgressService) {
        progress.state.subscribe(state => {
             state.active;  // (boolean) progress has started
             state.value;   // (number) progress value
        });
 }
```

**Comment by MurhafSousli** [comment]
@prosenjit-itobuz  See the doc https://github.com/MurhafSousli/ngx-progressbar#integrating-custom-loaders
