### ISSUE TITLE
[ShowSpinner] property

### ISSUE THREAD

**Issue by fsaina** [MurhafSousli/ngx-progressbar#56]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => search for a similar issue before submitting
[ ] feature request
[ ] question
```

**Minimal usage of the plugin**
When using [showSpinner]="'false'" property with inner quotation ('') the spinner is still shown. But passing a Boolean instead of a string => [showSpinner]="false" works as intended. Update doc.

**Comment by MurhafSousli** [comment]
Hi @fsaina , the docs mentions that

`[showSpinner]: boolean`


why would you write `'false'` instead of `false`!
