### ISSUE TITLE
Support HttpClient

### ISSUE THREAD

**Issue by zcsongor** [MurhafSousli/ngx-progressbar#57]
**I'm submitting a ...**
```
[ ] bug report => search for a similar issue before submitting
[X] feature request
[ ] question
```

Automagic right now does not support the new HttpClient. Could you provide an HttpClient edition?

Great library, thank you for your work!

Edit:
Temporarily you could update the README with @adrienlamotte's solution, providing that code snippet, with addition how to wire up an app with an http interceptor. Or I can submit a PR for that :)

**Comment by MurhafSousli** [comment]
Hi @zcsongor, yes It would be great if you can submit a PR

**Comment by zcsongor** [comment]
You can find my PR here: https://github.com/MurhafSousli/ngx-progressbar/pull/58
