### ISSUE TITLE
Unable to intercept requests permeating from "@angular/http"

### ISSUE THREAD

**Issue by RbkGh** [MurhafSousli/ngx-progressbar#63]
Setup to the project has been accomplished successfully in angular 4.3.0 project and the <ng-progress></ng-progress> tag has been placed in index.html but when there is an http request,the interception does not occur,thus the progress bar does not show although it's present in the dom when checked using chrome devtools.

**Comment by MurhafSousli** [comment]
For `@angular/http` use [**NgProgressBrowserXhr**](https://github.com/MurhafSousli/ngx-progressbar#automagic-loading-bar)

**Comment by RbkGh** [comment]
I did { provide: HTTP_INTERCEPTORS, useClass: NgProgressBrowserXhr, multi: true } but still the ng-progress does not show up .

**Comment by MurhafSousli** [comment]
@RbkGh Are you using **HttpClient** or **Http**? post your full usage code

**Comment by RbkGh** [comment]
i'm using Http.
this is the configuration for app.module.ts.

`import {NgProgressBrowserXhr,NgProgressModule} from 'ngx-progressbar';`
` import {BrowserXhr} from "@angular/http";               `
`....`
`imports: [`
`HttpModule,`
`NgProgressModule`
 ` ]`
`providers: [`
`{ provide: BrowserXhr, useClass: NgProgressBrowserXhr }`
`]`

**Comment by MurhafSousli** [comment]
Here is a working [plunkr](https://plnkr.co/edit/LGTdFQCDBnT4wqlEAu5z?p=preview)

**Comment by RbkGh** [comment]
if you are using angular-cli,do you need to do any special configuration for ngx-progressbar.umd.js to be discovered ?

**Comment by RbkGh** [comment]
hi,it works now,I had to load it into the parent component file. ie app.component.html
