### ISSUE TITLE
import NgProgressModule

### ISSUE THREAD

**Issue by huangyangyang-yangyang** [MurhafSousli/ngx-progressbar#71]
import NgProgressModule,have as below error:

ERROR in ./src/app/shared/shared.module.ts
Module not found: Error: Can't resolve 'ngx-progressbar/index' in 'D:\work file\
 @ ./src/app/shared/shared.module.ts 33:0-57
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi webpack-dev-server/client?http://localhost:4200 ./src/main.ts
run error

**Comment by MurhafSousli** [comment]
post your usage code

**Comment by huangyangyang-yangyang** [comment]
import {NgProgressModule} from "ngx-progressbar/index";
@NgModule({
  imports: [
      NgProgressModule,
  ],

just write this, compile fail

**Comment by huangyangyang-yangyang** [comment]
ngx-progressbar/index ，this is Editor prompt

**Comment by MurhafSousli** [comment]
@huangyangyang-yangyang try it without index, you should follow the docs not the editor prompt

**Comment by huangyangyang-yangyang** [comment]
try it without index，still compile fail

**Comment by huangyangyang-yangyang** [comment]
I don't know why？

**Comment by huangyangyang-yangyang** [comment]
successfully,  thanks.
