### ISSUE TITLE
Ignore Http requests

### ISSUE THREAD

**Issue by shobhitvaish** [MurhafSousli/ngx-progressbar#74]
Dear,

I'm submitting a question or feature request
Is there a way to ignore a HTTP request while using automagic loading bar? If not, are you planning to add it soon?
Ideally I would like to have some regex which either accept route or api end points which are ignored while using automagic loading bar.

Unfeigned regards,
Shobhit Vaish

**Comment by MurhafSousli** [comment]
Hi @shobhitvaish, This is on my radar actually, I will add more features soon

**Comment by shobhitvaish** [comment]
Thanks! That would be awesome.
Do you have a date by when this would be implemented?

**Comment by MurhafSousli** [comment]
@shobhitvaish Nope, currently I am working on another projects, but I will come back to this one once I am done

**Comment by shobhitvaish** [comment]
Thanks!

**Comment by MurhafSousli** [comment]
Will track this issue in #83
