### ISSUE TITLE
AOT build issue

### ISSUE THREAD

**Issue by jigarpt** [MurhafSousli/ngx-progressbar#75]
**I'm submitting a ...**  (check one with "x")
```
[ x] bug report => search for a similar issue before submitting
[ ] feature request
[ ] question
```
Versions:
ngx-progressbar => 2.0.8
angular => 4.1.3

Usage: (app.module.ts)

Imports
HttpModule
NgProgressModule

Providers
{ provide: BrowserXhr, useClass: NgProgressBrowserXhr }

Using automatic loading bar.

AOT compilation issue.
ngx-progressbar/src/services/interceptor.provider.d.ts:1:70: Cannot find module '@angular/common/http'.

Looking forward for any inputs / comments. 

Thanks.

**Comment by MurhafSousli** [comment]
Hi @jigarpt, I can't see your code, but this error means that you are using the `NgProgressInterceptor` when you should not.  in `4.1.3` you can not use the interceptor.

**Comment by jigarpt** [comment]
Hi @MurhafSousli , Thanks a lot for your prompt response. 

I do agree with you that with Angular 4.1.3, NgProgressInterceptor should not be used. I followed steps, and used NgProgressBrowserXhr. Below is my provider configuration. 

{ provide: BrowserXhr, useClass: NgProgressBrowserXhr }

Any direction to identify an issue, will be helpful. 

Thanks.

**Comment by MurhafSousli** [comment]
@jigarpt this is a bug in Angular https://github.com/angular/angular/issues/13590. AOT compiler is compiling any file that exists in the directory no matter if you use it or not

**Comment by MurhafSousli** [comment]
A current workaround now is to remove the unused plug in `node_modules/ngx-progressbar`

**Comment by jigarpt** [comment]
@MurhafSousli  Thanks a ton for your response; I will try that and get back to you. 

Once again thank you.

**Comment by MurhafSousli** [comment]
@jigarpt  I am closing this as not an issue, but feel free to reopen if you still have the problem

**Comment by jigarpt** [comment]
@MurhafSousli  np, Thank you. 👍
