### ISSUE TITLE
Error: Cannot find module @angular/common/http

### ISSUE THREAD

**Issue by bhagath007** [MurhafSousli/ngx-progressbar#77]
Hi,

I am using angular 4.2.6 version. I have installed ngx-progressbar and I have integrated automagic progress bar on every http call.

It's working perfectly!
But while running package with prod profile I am getting an error as below:

Error: Cannot find module @angular/common/http

Please help me out!

Thanks
Bhagath

**Comment by fchiumeo** [comment]
you use NgProgressBrowserXhr or NgProgressInterceptor ?
NgProgressBrowserXhr  use HttpModule 
NgProgressInterceptor use HttpClientModule

**Comment by bhagath007** [comment]
I Used NgProgressBrowserXhr

**Comment by MurhafSousli** [comment]
This is a bug in **ngc**, this is a dup of #75, let's track the issue there

**Comment by ivanovvitaly** [comment]
Have the same error Cannot find module '@angular/common/http'.

using angular 4.2.6 not AOT

**Comment by MurhafSousli** [comment]
@ivanovvitaly did you follow the fix in #75 ?

**Comment by ivanovvitaly** [comment]
Decided to upgrade to angular 4.4, wasn't big deal for us, problem gone. Thanks

**Comment by arivasvera** [comment]
@bhagath007 try with `2.0.3` version: `npm install ngx-progressbar@2.0.3 --save`

**Comment by IP-Andro** [comment]
@MurhafSousli / @fchiumeo  , I am facing the same issue while using NgProgressBrowserXhr .

I installed Angular ( version 2.4.10 ) and 2.1.1 version of ngx-progressbar .
The documentation on [page  ](https://github.com/MurhafSousli/ngx-progressbar/wiki)is saying to use NgProgressBrowserXhr for Angular version 2 . 
Below is my provider configuration.
`{ provide: BrowserXhr, useClass: NgProgressBrowserXhr }`

So , still facing `Cannot find module '@angular/common/http'`

Can you please suggest a workaround , as the workaround ( suggested in #75  ) of **_removing unused plugin_**` node_modules/ngx-progressbar` is not clear .

**Comment by MurhafSousli** [comment]
@IP-Andro in `node_modules/ngx-progressbar` you will find two files, **NgProgressBrowserXhr** and **NgProgressInterceptor**, I don't remember the exact name for the files, but it is easy to tell. just remove **NgProgressInterceptor** and it should work.

**Comment by IP-Andro** [comment]
@MurhafSousli  , Thanks for a quick response . 

But this will be a manual workaround . I build my application from Jenkins automation tool . So , there i will not be able to automatically delete this file - '**NgProgressInterceptor**' while generating a production build .  Please correct me if I missed something .

**Comment by MurhafSousli** [comment]
@IP-Andro For v2.x that is right, read [#75](https://github.com/MurhafSousli/ngx-progressbar/issues/75) for more details.

**Comment by IP-Andro** [comment]
@MurhafSousli, so you mean that since it's a bug in angular/angular#13590. AOT compiler is compiling any file that exists in the directory no matter if you use it or not.


so, either i will have to upgrade angular version to 4 or i will have to leave this bug as it is . 

Please correct me if i am wrong .

**Comment by MurhafSousli** [comment]
@IP-Andro Yupp

**Comment by IP-Andro** [comment]
@MurhafSousli  , Thanks for the acknowledgement .

**Comment by victorlenz** [comment]
@arivasvera downgrading to 2.0.3 resolves the error on angular 4.1.1. But the loader is not showing. any idea?
