### ISSUE TITLE
'ng-progress' is not a known element

### ISSUE THREAD

**Issue by cr1t** [MurhafSousli/ngx-progressbar#78]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search for a similar issue before submitting
[ ] feature request
[x ] question
```
I'm trying to add ngx-progressbar to ng2-admin

I'm getting this error

'ng-progress' is not a known element:
1. If 'ng-progress' is an Angular component, then verify that it is part of this module.
2. If 'ng-progress' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message. ("
    [ERROR ->]<ng-progress></ng-progress>
	<ba-sidebar></ba-sidebar>
    <ba-page-top></ba-page-top>
"): ng:///PagesModule/Pages.html@1:4

My template looks like this below, and I followed the rest of the instruction, any ideas?

 template: `
    <ng-progress></ng-progress>
	<ba-sidebar></ba-sidebar>
    <ba-page-top></ba-page-top>
    <div class="al-main">
      <div class="al-content">
        <ba-content-top></ba-content-top>
        <router-outlet></router-outlet>
      </div>
    </div>
    <footer class="al-footer clearfix">
      <div class="al-footer-right" translate>{{'general.created_with'}} <i class="ion-heart"></i></div>
      <div class="al-footer-main clearfix">
        <div class="al-copy">&copy; <a href="http://akveo.com" translate>{{'general.akveo'}}</a> 2016</div>
        <ul class="al-share clearfix">
          <li><i class="socicon socicon-facebook"></i></li>
          <li><i class="socicon socicon-twitter"></i></li>
          <li><i class="socicon socicon-google"></i></li>
          <li><i class="socicon socicon-github"></i></li>
        </ul>
      </div>
    </footer>
    <ba-back-top position="200"></ba-back-top>
    `

**Comment by MurhafSousli** [comment]
Hi @cr1t, Yes you need to import the `NgProgressModule`

**Comment by cr1t** [comment]
I had to include it in my pages.module like this also, Thanks, I'm a bit new to Angular 4 still

`import { NgModule }      from '@angular/core';
import { CommonModule }  from '@angular/common';

import { routing }       from './pages.routing';
import { NgaModule } from '../theme/nga.module';
import { AppTranslationModule } from '../app.translation.module';

import { Pages } from './pages.component';
import { NgProgressModule } from 'ngx-progressbar';
@NgModule({
  imports: [CommonModule, AppTranslationModule, NgaModule, routing,NgProgressModule],
  declarations: [Pages]
})
export class PagesModule {
}
`
