### ISSUE TITLE
Proposition: Add XHR status events

### ISSUE THREAD

**Issue by PawelOwczarekFalcon** [MurhafSousli/ngx-progressbar#79]
https://github.com/chieffancypants/angular-loading-bar

Above library has events related to XHR status, for example: cfpLoadingBar:completed: triggered once when the all XHR requests have returned (either successfully or not)

Is possible to add similar mechanism to your lib ?

**Comment by MurhafSousli** [comment]
@PawelOwczarekFalcon This is already possible using the **NgProgressService**
```ts
NgProgressService.state.subscribe(state => state.active)
``` 
But I will add a `(done)` event in the next update
