### ISSUE TITLE
ObjectUnsubscribedError when changing the route from one component to other component

### ISSUE THREAD

**Issue by kunal1111** [MurhafSousli/ngx-progressbar#82]
I am using ngx-progressbar component in Angular 4. Progress is getting displayed and works great until I navigate to other component. I get object unsubscribed error when I navigate back to component where I have used progressbar component. Below is error stack trace.

ERROR e {name: "ObjectUnsubscribedError", stack: "ObjectUnsubscribedError: object unsubscribed↵    a…rd/vendor.60e9e8d42871ad10a7ac.bundle.js:1:54553)", message: "object unsubscribed"}message: "object unsubscribed"name: "ObjectUnsubscribedError"stack: "ObjectUnsubscribedError: object unsubscribed↵    at new e (http://localhost:8080/PDCCDashboard/vendor.60e9e8d42871ad10a7ac.bundle.js:1:457548)↵    at e.next (http://localhost:8080/PDCCDashboard/vendor.60e9e8d42871ad10a7ac.bundle.js:1:1616174)↵    at t.W9ph.t.updateState (http://localhost:8080/PDCCDashboard/vendor.60e9e8d42871ad10a7ac.bundle.js:1:609611)↵    at t.W9ph.t.set (http://localhost:8080/PDCCDashboard/vendor.60e9e8d42871ad10a7ac.bundle.js:1:609227)↵    at t.W9ph.t.start (http://localhost:8080/PDCCDashboard/vendor.60e9e8d42871ad10a7ac.bundle.js:1:608793)↵    at l.getHomePageData (http://localhost:8080/PDCCDashboard/main.4b6c274b2e629c249170.bundle.js:1:65406)↵    at l.ngOnInit (http://localhost:8080/PDCCDashboard/main.4b6c274b2e629c249170.bundle.js:1:65174)↵    at Cn (http://localhost:8080/PDCCDashboard/vendor.60e9e8d42871ad10a7ac.bundle.js:1:40225)↵    at pi (http://localhost:8080/PDCCDashboard/vendor.60e9e8d42871ad10a7ac.bundle.js:1:55020)↵    at ui (http://localhost:8080/PDCCDashboard/vendor.60e9e8d42871ad10a7ac.bundle.js:1:54553)"__proto__: Error
_ @ vendor.60e9e8d42871ad10a7ac.bundle.js:1
t.handleError @ vendor.60e9e8d42871ad10a7ac.bundle.js:1
(anonymous) @ vendor.60e9e8d42871ad10a7ac.bundle.js:1
t.invoke @ polyfills.86c0b4d44f70fee7f41e.bundle.js:1
r.run @ polyfills.86c0b4d44f70fee7f41e.bundle.js:1
t.runOutsideAngular @ vendor.60e9e8d42871ad10a7ac.bundle.js:1
e.tick @ vendor.60e9e8d42871ad10a7ac.bundle.js:1
(anonymous) @ vendor.60e9e8d42871ad10a7ac.bundle.js:1
t.invoke @ polyfills.86c0b4d44f70fee7f41e.bundle.js:1
onInvoke @ vendor.60e9e8d42871ad10a7ac.bundle.js:1
t.invoke @ polyfills.86c0b4d44f70fee7f41e.bundle.js:1
r.run @ polyfills.86c0b4d44f70fee7f41e.bundle.js:1
t.run @ vendor.60e9e8d42871ad10a7ac.bundle.js:1
next @ vendor.60e9e8d42871ad10a7ac.bundle.js:1
e.object.o @ vendor.60e9e8d42871ad10a7ac.bundle.js:1
T14+.e.__tryOrUnsub @ vendor.60e9e8d42871ad10a7ac.bundle.js:1
T14+.e.next @ vendor.60e9e8d42871ad10a7ac.bundle.js:1
T14+.e._next @ vendor.60e9e8d42871ad10a7ac.bundle.js:1
T14+.e.next @ vendor.60e9e8d42871ad10a7ac.bundle.js:1
e.next @ vendor.60e9e8d42871ad10a7ac.bundle.js:1
e.emit @ vendor.60e9e8d42871ad10a7ac.bundle.js:1
ot @ vendor.60e9e8d42871ad10a7ac.bundle.js:1
onHasTask @ vendor.60e9e8d42871ad10a7ac.bundle.js:1
t.hasTask @ polyfills.86c0b4d44f70fee7f41e.bundle.js:1
t._updateTaskCount @ polyfills.86c0b4d44f70fee7f41e.bundle.js:1
r._updateTaskCount @ polyfills.86c0b4d44f70fee7f41e.bundle.js:1
r.runTask @ polyfills.86c0b4d44f70fee7f41e.bundle.js:1
o @ polyfills.86c0b4d44f70fee7f41e.bundle.js:1
e.invokeTask @ polyfills.86c0b4d44f70fee7f41e.bundle.js:1
h @ polyfills.86c0b4d44f70fee7f41e.bundle.js:1
v @ polyfills.86c0b4d44f70fee7f41e.bundle.js:1

**Comment by MurhafSousli** [comment]
Hi @kunal1111, This issue has been addressed many times, please check previous issues before submitting

Put `<ng-progress></ng-progress>` in your root component

dup #41 #28 #27

**Comment by kunal1111** [comment]
Thanks MurhafSousli for prompt response. Issue got resolved after making changes as per your suggestion.

**Comment by marcopall** [comment]
I didn't use the ng-progress but I have the same error, with the same behaviour if I visit a page and leave for another, when I come back I have this error, enclosed the files of the component, app module and routing:

[errori.zip](https://github.com/MurhafSousli/ngx-progressbar/files/1768384/errori.zip)

:

ERROR Error: Uncaught (in promise): ObjectUnsubscribedError: object unsubscribed
ObjectUnsubscribedError: object unsubscribed
    at new ObjectUnsubscribedError (ObjectUnsubscribedError.js:21)
    at Subject._trySubscribe (Subject.js:95)
    at Subject.Observable.subscribe (Observable.js:160)
    at new PannelloInserimentoComponent (pannello-inserimento.component.ts:87)
    at createClass (core.js:12167)
    at createDirectiveInstance (core.js:12010)
    at createViewNodes (core.js:13448)
    at createRootView (core.js:13338)
    at callWithDebugContext (core.js:14739)
    at Object.debugCreateRootView [as createRootView] (core.js:14040)
    at new ObjectUnsubscribedError (ObjectUnsubscribedError.js:21)
    at Subject._trySubscribe (Subject.js:95)
    at Subject.Observable.subscribe (Observable.js:160)
    at new PannelloInserimentoComponent (pannello-inserimento.component.ts:87)
    at createClass (core.js:12167)
    at createDirectiveInstance (core.js:12010)
    at createViewNodes (core.js:13448)
    at createRootView (core.js:13338)
    at callWithDebugContext (core.js:14739)
    at Object.debugCreateRootView [as createRootView] (core.js:14040)
    at resolvePromise (zone.js:824)
    at resolvePromise (zone.js:795)
    at eval (zone.js:873)
    at ZoneDelegate.invokeTask (zone.js:425)
    at Object.onInvokeTask (core.js:4617)
    at ZoneDelegate.invokeTask (zone.js:424)
    at Zone.runTask (zone.js:192)
    at drainMicroTaskQueue (zone.js:602)
    at ZoneTask.invokeTask [as invoke] (zone.js:503)
    at invokeTask (zone.js:1540)

**Comment by MurhafSousli** [comment]
@marcopall can you reproduce your issue in https://stackblitz.com/edit/ngx-progressbar-router
