### ISSUE TITLE
How to disable progress bar for different API requests ?

### ISSUE THREAD

**Issue by PawelOwczarekFalcon** [MurhafSousli/ngx-progressbar#83]
How to disable progress bar for different API requests ? is it possible at all?

**Comment by MurhafSousli** [comment]
@PawelOwczarekFalcon No, it is not possible with the current version

**Comment by MurhafSousli** [comment]
@PawelOwczarekFalcon Do you have the design idea for this, how would the usage become like?

**Comment by MurhafSousli** [comment]
Will add this feature when https://github.com/angular/angular/issues/18155 is merged

**Comment by lazyspark** [comment]
@PawelOwczarekFalcon this can be done if you are using the core module and triggering the this.progress.start() and this.progress.done(). 

The hack is similar to hack for angular to say skip a request execute an interceptor. You add custom header in the request for requests you want to skip and you check header interceptor for the custom header and skip loader.

**Comment by nasserghiasi** [comment]
this.progressBar.complete() doesn't work in http intercenpor
do not anything

**Comment by Bodeclas** [comment]
@lazyspark I want skip a request but I'm using Automagic loading bar, is it possible?

**Comment by lazyspark** [comment]
Sorry didn’t get your question

**Comment by Bodeclas** [comment]
@lazyspark I don't want to show the bar in a specific api request, Is it possible? How can I do it?

**Comment by lazyspark** [comment]
In the interceptor for angular you can check the api url and not run progress.start for those requests. If you want to know how to do that for Angular - search for Http interceptor in angular. 

Above is not elegant solution and means you will predefined API URL for which you don’t need progress bar.

**Comment by Bodeclas** [comment]
@lazyspark Thanks! I will try it!

**Comment by juanjoseadan** [comment]
Maybe it is too late, but I found a "smart" way to hide it. You can try and see if it works for you

I made this "trick" in my token interceptor:

`
const ngProgress = document.getElementsByTagName('ng-progress');

if (ngProgress && request.url.includes('HERE YOU NEED TO PUT THE SERVICE URL YOU DONT WANT TO SHOW THE LOADING BAR')) {
	ngProgress.item(0)['style'].display = 'none';
} else {
	ngProgress.item(0)['style'].display = '';
}

request = request.clone({
	setHeaders: {
		Authorization: `Bearer ${this.token}`
	}
});
`
