### ISSUE TITLE
use HttpXhrBackend instead XHRBackend 

### ISSUE THREAD

**Issue by pranee1h** [MurhafSousli/ngx-progressbar#84]
**I'm submitting a ...**  (check one with "x")
```
[ x] bug report => search for a similar issue before submitting
[ ] feature request
[ ] question
```

**Minimal usage of the plugin**

In ngx-progressbar/src/services/browser-xhr.provider.ts change the 
`import { XHRBackend } from '@angular/http'; `
 to 
`import { HttpXhrBackend } from '@angular/common/http';`
--

**Comment by MurhafSousli** [comment]
@pranee1h  It is unclear what you are asking for! what is the error?

**Comment by pranee1h** [comment]
ngx-progressbar/src/services/browser-xhr.provider.ts this file still uses the deprecated http. Please upgrade to common/http.

**Comment by fchiumeo** [comment]
https://github.com/MurhafSousli/ngx-progressbar#automagic-loading-bar

NgProgressBrowserXhr  is for angular < 4.3

**Comment by pranee1h** [comment]
Build fails if we remove `@angular/http`

**Comment by MurhafSousli** [comment]
@pranee1h Give me details, your usage, the error that you are getting and which angular version are you using
