### ISSUE TITLE
.../ngx-pogressbar/index.d.ts' is not a module.

### ISSUE THREAD

**Issue by ogezue** [MurhafSousli/ngx-progressbar#90]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search for a similar issue before submitting
[ ] feature request
[ ] question
```

**Minimal usage of the plugin**

Problem 'ngx-progressbar' is marked red by IDE: .../ngx-pogressbar/index.d.ts' is not a module.

**Comment by MurhafSousli** [comment]
@ogezue show me your code

**Comment by HarelM** [comment]
Same error here:
```
ERROR in C:/projects/site/IsraelHiking.Web/sources/$$_gendir/application/application.module.ngfactory.ts (241,70): Property 'NgProgressService' does not exist on type 'typeof "C:/projects/site/IsraelHiking.Web/node_modules/ngx-progressbar/index"'.
ERROR in C:/projects/site/IsraelHiking.Web/sources/application/services/file.service.ts (4,10): Module '"C:/projects/site/IsraelHiking.Web/node_modules/ngx-progressbar/index"' has no exported member 'NgProgressService'.
```
I saw this error also in the following package:
https://github.com/michaelbromley/ngx-pagination/issues/210
Something to do with upgrading angular version.
Failing build can be found here:
https://ci.appveyor.com/project/IsraelHikingHost/site/build/5.1.44
I'm reverting back to `2.0.8`.

**Comment by TRAHOMOTO** [comment]
Yep! I'm fall in this trap too, seems guys rename NgProgressService to NgProgress

**Comment by ogezue** [comment]
@HarelM 2.0.8 has a another bug that has been fixed yesterday.

@MurhafSousli What do you want to see? It is exactly as in your documentation. Problem is that I get an error with this line:
`import { NgProgress } from 'ngx-progressbar';`

**Comment by HarelM** [comment]
If this is the case (change `NgProgessService` to `NgProgress`) the version number is incorrect as this is a breaking change and the minor number of the version should've been changed.
My `package.json` had this rule: `"ngx-progressbar": "^2.0.8",` and my build failed because it was using `2.0.11`.

**Comment by ogezue** [comment]
but the current version is 2.1.1

**Comment by HarelM** [comment]
Sorry, my mistake, should've used `~` instead of `^`.

**Comment by MurhafSousli** [comment]
@ogezue 2.0.8 doesn't really have bugs, we just allowed the component to be used anywhere instead of only in the root component, check [the changelog](https://github.com/MurhafSousli/ngx-progressbar/blob/master/CHANGELOG.md)

@ogezue checkout your package.json again, it could be that npm is caching the old version and using it again (sometimes it happens), I think the best way to know is to reproduce the error you are getting in this [stackblitz](https://stackblitz.com/edit/ngx-progressbar)

**Comment by ogezue** [comment]
It is a lint problem - but the solution is working.
