### ISSUE TITLE
progressService.start() is not working when used in a component used in a lazy module

### ISSUE THREAD

**Issue by nicoguefveneu** [MurhafSousli/ngx-progressbar#91]
Hi,

I'm trying to use the progressService.start() and progressService.done() on a component used a lazy module ('/search') but nothing is hapenning (no error either).

It works well on the home module which is not lazy with the same component.

I have found this :
https://github.com/MurhafSousli/ngx-progressbar/issues/65

I tested with the 2.0.8 version and I still got the problem.

configuration code :
app.module
`@NgModule({
imports: [
NgProgressModule
`

maye there is something to configure in the shared module ?

I had to do the following for a service shared between the home module and the search (lazy module)

`export class SharedModule {
  public static forRoot(): ModuleWithProviders {
    // put stuff here (like singleton) to be shared with lazy modules
    return {
      ngModule: SharedModule,
      providers: [SearchService]
    };
  }
}`

Thanks !

**Comment by MurhafSousli** [comment]
Hi @nicoguefveneu if you want the progress bar in a lazy module, just import **NgProgressModule** in the lazy module, here is a working [stackblitz](https://stackblitz.com/edit/angular-lazy-loading-bgy9gy?file=app/lazy/lazy.component.ts) for lazy modules

**Comment by nicoguefveneu** [comment]
Hi @MurhafSousli, thanks but I would like to have a single '<ng-progress></ng-progress>' in the 'app.component.html' ot have it only once in all the app, and in this case it's not working, see a fork here :
https://angular-lazy-loading-y5sn2x.stackblitz.io/lazy

Is there a way to do so ?

**Comment by MurhafSousli** [comment]
@nicoguefvene I don't see the problem! what do you want to have? please send me the editor link of the stackblitz not the preview

**Comment by nicoguefveneu** [comment]
sorry @MurhafSousli, here is the editor link :
https://stackblitz.com/edit/angular-lazy-loading-y5sn2x?file=app%2Fapp.component.html

**Comment by MurhafSousli** [comment]
@nicoguefveneu It is not starting because the lazy module has different instance of the progress. As far I understand, you want to show the progress while the lazy module is loading!

This should be fixed this by implementing `forRoot()` or `forChild()`

**Comment by nicoguefveneu** [comment]
exactly @MurhafSousli, that's what I thought when I wrote the first post. I tried something but I couldn't manage to make it work, could you write an example with stackblitz ?
Thanks

**Comment by MurhafSousli** [comment]
@nicoguefveneu I think you can do this differently, but first remove `NgProgressModule` from your lazy module then use router event to start and end the progress 

in *app.component.ts*
```ts
  ngOnInit() {

    this.router.events
      .subscribe((event) => {
        if (event instanceof NavigationStart) {
          this.progress.start();
          console.log('Start');
        } else if (event instanceof NavigationEnd) {
          this.progress.done();
          console.log('Done');
        }
      });
  }
```
[Fixed stackblitz](https://stackblitz.com/edit/angular-lazy-loading-g9eoyr?file=app%2Fapp.component.ts)

**Comment by nicoguefveneu** [comment]
Hi @MurhafSousli this is very informative !

I have anotheruse case :
https://stackblitz.com/edit/angular-lazy-loading-y5sn2x?file=app%2Fshared%2Fcomponents%2Fsearch%2Fsearch.component.ts

I can't manage to make it work on the stackblitz, i'm triing to have a searchComponent and to have the progress bar in the helloComponent as well as in the lazy component.

Any idea how to achieve this ?

**Comment by MurhafSousli** [comment]
@nicoguefveneu https://stackblitz.com/edit/angular-lazy-loading-hnuvxt

**Comment by nicoguefveneu** [comment]
Thanks a lot @MurhafSousli !
I could figure out what was the problem.
The app is of course more complex, but the problem was due to a second component with a n import of the progressModule, and it was ovveriding the instance of the app.module..
I don't know if it's clear, anyways problem solved 👍 
Cheers

**Comment by MurhafSousli** [comment]
@nicoguefveneu Yes, this is exactly what I did, I removed the extra **NgProgressModule** from your lazy module.. 
Cheers!
