### ISSUE TITLE
Spinner position.

### ISSUE THREAD

**Issue by nblavoie** [MurhafSousli/ngx-progressbar#92]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search for a similar issue before submitting
[x ] feature request
[ ] question
```

**Minimal usage of the plugin**
That would be nice to change the spinner side with a property [spinnerSide]: 'left', 'center', or 'right'.

**Comment by MurhafSousli** [comment]
Hi @nblavoie, I will look into this in the future update
