### ISSUE TITLE
AOT build with ngtools/webpack fails on root module

### ISSUE THREAD

**Issue by davidkudera** [MurhafSousli/ngx-progressbar#95]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
- [ ] question
```

### OS and Version?
Ubuntu 17.04

### Versions
node: v8.9.1
yarn: 1.3.2
ngx-progressbar/core: 3.0.0
angular/cli: 5.0.3
ngtools/webpack: 1.8.4

### Repro steps
```bash
$ yarn add @ngx-progressbar/core
```

Register module to root `AppModule`:

```typescript
import {NgModule} from '@angular/core';
import {BrowserModule} from '@angular/platform-browser';
import {NgProgressModule} from '@ngx-progressbar/core';

import {AppRoutingModule} from './app-routing.module';
import {AppComponent} from './app.component';


@NgModule({
	imports: [
		BrowserModule,
		NgProgressModule.forRoot(),
		AppRoutingModule,
	],
	declarations: [
		AppComponent,
	],
	bootstrap: [AppComponent],
})
export class AppModule {}
```

### The log given by the failure
```
ERROR in Error: Error encountered resolving symbol values statically. Calling function 'NgProgressModule', function calls are not supported. Consider replacing the function or lambda with a reference to an exported function, resolving symbol AppModule in /path/to/app.module.ts, resolving symbol AppModule in /path/to/app.module.ts
```

### Desired functionality
Being able to compile the project with ngx-progressbar.

### Mention any other details that might be useful

I'm using `@ngtools/webpack` with `webpack`.

**Comment by MurhafSousli** [comment]
I think this is related to this bug [#17663](https://github.com/angular/angular/issues/17663)

**Comment by davidkudera** [comment]
That is awesome, thank you 👍 

Do you plan to tag a new version? I tried to install your package from `master` branch, but that of course installs the `@ngx-progressbar/demo` package.

**Comment by MurhafSousli** [comment]
@davidkudera welcome 😄
I am not sure how to install it from github directly, the `package.json` in the root dir is meant for the demo, the library's one is in `lib/core`

**Comment by davidkudera** [comment]
Thats fine, I'll just wait for a new release 😉 . Thanks again

**Comment by MurhafSousli** [comment]
@davidkudera I will release one now, but will that make any difference, I think it will still point to the root package.json, right?

**Comment by davidkudera** [comment]
Depends on if you'll release new versions on npm also. You're correct that just tagging woudn't be enough.
