### ISSUE TITLE
Documentation not updated

### ISSUE THREAD

**Issue by KatzeKahn** [MurhafSousli/ngx-progressbar#96]
### Bug Report or Feature Request (mark with an `x`)
```
- [x ] bug report -> please search issues before submitting
- [ ] feature request
- [ ] question
```
1) The documention is not updated accordingly to the new version 3.0.0. It still says that 'showSpinner' is an attribute which is 'spinner' now.

2) And btw, it seems there is an issue with npm install. Console always outputs the error message:

```
+-- UNMET PEER DEPENDENCY @angular/common@5.0.5
+-- UNMET PEER DEPENDENCY @angular/compiler@5.0.5
`-- UNMET PEER DEPENDENCY @angular/core@5.0.5
```
   which is actually installed on my system.

**Comment by MurhafSousli** [comment]
@KatzeKahn 
1. Thanks for noticing, will update this
2. This could be caused by different package! have a look at the peerDependencies [here](https://github.com/MurhafSousli/ngx-progressbar/blob/master/build/core/package.json)

**Comment by KatzeKahn** [comment]
Alrighty, but link does not work (404)

**Comment by MurhafSousli** [comment]
@KatzeKahn Can you try and confirm

**Comment by KatzeKahn** [comment]
I checked but there should be no problems. I've got Angular 5.0.5 installed for all packages.

`npm install --save @ngx-progressbar/core` throws error as stated above.
A later `npm install` displays no error output.
